In [1]:
# load libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("coffee_sales.csv")

In [4]:
data

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [6]:
data.describe()

             money
count  3636.000000
mean     31.746859
std       4.919926
min      18.120000
25%      27.920000
50%      32.820000
75%      35.760000
max      40.000000

In [7]:
data.head() # to see first 5 rows of data

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [8]:
data.tail() # to see last five rows of data

,date,datetime,cash_type,card,money,coffee_name
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [10]:
data.shape # columns and rows in the data

(3636, 6)

In [11]:
# data cleaning

In [12]:
# checling the missing values

In [14]:
data.isna().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [15]:
data['card']

0       ANON-0000-0000-0001
1       ANON-0000-0000-0002
2       ANON-0000-0000-0002
3       ANON-0000-0000-0003
4       ANON-0000-0000-0004
               ...
3631    ANON-0000-0000-1158
3632    ANON-0000-0000-1315
3633    ANON-0000-0000-1315
3634    ANON-0000-0000-1316
3635    ANON-0000-0000-1275
Name: card, Length: 3636, dtype: object

In [16]:
# how to see the full data

In [17]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
print(data)

            date                 datetime cash_type                 card  \
0     2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001
1     2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002
2     2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002
3     2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003
4     2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004
5     2024-03-01  2024-03-01 15:39:47.726      card  ANON-0000-0000-0005
6     2024-03-01  2024-03-01 16:19:02.756      card  ANON-0000-0000-0006
7     2024-03-01  2024-03-01 18:39:03.580      card  ANON-0000-0000-0007
8     2024-03-01  2024-03-01 19:22:01.762      card  ANON-0000-0000-0008
9     2024-03-01  2024-03-01 19:23:15.887      card  ANON-0000-0000-0008
10    2024-03-01  2024-03-01 19:29:17.391      card  ANON-0000-0000-0009
11    2024-03-02  2024-03-02 10:22:06.957      card  ANON-0000-0000-0010
12    2024-03-02  2024-03-02 10:30:35.668      cash                  NaN
13    2024-03-02  2024-03-02 10:41:41.249      card  ANON-0000-0000-0011
14    2024-03-02  2024-03-02 11:59:45.484      card  ANON-0000-0000-0012
15    2024-03-02  2024-03-02 14:38:35.535      card  ANON-0000-0000-0013
16    2024-03-02  2024-03-02 16:37:24.475      card  ANON-0000-0000-0014
17    2024-03-02  2024-03-02 17:34:54.969      card  ANON-0000-0000-0004
18    2024-03-03  2024-03-03 10:10:43.981      cash                  NaN
19    2024-03-03  2024-03-03 10:27:18.561      card  ANON-0000-0000-0015
20    2024-03-03  2024-03-03 11:33:56.118      card  ANON-0000-0000-0016
21    2024-03-03  2024-03-03 12:26:56.098      card  ANON-0000-0000-0012
22    2024-03-03  2024-03-03 13:09:36.321      card  ANON-0000-0000-0017
23    2024-03-03  2024-03-03 17:06:40.271      card  ANON-0000-0000-0018
24    2024-03-03  2024-03-03 17:08:45.895      card  ANON-0000-0000-0019
25    2024-03-03  2024-03-03 18:03:23.369      card  ANON-0000-0000-0020
26    2024-03-03  2024-03-03 18:04:27.946      card  ANON-0000-0000-0020
27    2024-03-03  2024-03-03 18:08:04.959      card  ANON-0000-0000-0020
28    2024-03-04  2024-03-04 10:03:51.994      card  ANON-0000-0000-0001
29    2024-03-04  2024-03-04 10:54:50.958      card  ANON-0000-0000-0021
30    2024-03-04  2024-03-04 11:05:16.184      card  ANON-0000-0000-0012
31    2024-03-04  2024-03-04 14:04:37.734      card  ANON-0000-0000-0022
32    2024-03-05  2024-03-05 09:59:52.651      card  ANON-0000-0000-0001
33    2024-03-05  2024-03-05 14:34:55.963      card  ANON-0000-0000-0023
34    2024-03-05  2024-03-05 17:34:06.043      card  ANON-0000-0000-0024
35    2024-03-05  2024-03-05 17:35:25.021      card  ANON-0000-0000-0025
36    2024-03-05  2024-03-05 17:36:28.571      card  ANON-0000-0000-0026
37    2024-03-05  2024-03-05 17:37:13.659      card  ANON-0000-0000-0027
38    2024-03-05  2024-03-05 17:38:09.354      card  ANON-0000-0000-0009
39    2024-03-05  2024-03-05 17:56:15.776      card  ANON-0000-0000-0028
40    2024-03-05  2024-03-05 18:01:31.242      card  ANON-0000-0000-0028
41    2024-03-06  2024-03-06 12:30:27.089      cash                  NaN
42    2024-03-06  2024-03-06 13:24:07.667      card  ANON-0000-0000-0012
43    2024-03-06  2024-03-06 13:25:14.351      card  ANON-0000-0000-0012
44    2024-03-06  2024-03-06 14:52:01.761      card  ANON-0000-0000-0029
45    2024-03-06  2024-03-06 14:53:18.344      card  ANON-0000-0000-0029
46    2024-03-07  2024-03-07 10:08:58.945      cash                  NaN
47    2024-03-07  2024-03-07 10:18:40.543      card  ANON-0000-0000-0030
48    2024-03-07  2024-03-07 11:03:58.976      card  ANON-0000-0000-0031
49    2024-03-07  2024-03-07 11:25:43.977      cash                  NaN
50    2024-03-07  2024-03-07 15:40:22.606      card  ANON-0000-0000-0032
51    2024-03-07  2024-03-07 15:41:28.784      card  ANON-0000-0000-0033
52    2024-03-08  2024-03-08 10:34:41.283      card  ANON-0000-0000-0012
53    2024-03-08  2024-03-08 12:22:28.653      card  ANON-0000-0000-0034
54    2024-03-08  2024-03-08 13:53:02.042      card  ANON-0000-0000-0035
55    2024-03-08  2024-03-08 14:44:12.686      card  ANON-0000-0000-0012
56    2024-03-08  2024-03-08 14:45:11.048      card  ANON-0000-0000-0033
57    2024-03-08  2024-03-08 14:46:11.155      card  ANON-0000-0000-0012
58    2024-03-08  2024-03-08 18:57:51.451      card  ANON-0000-0000-0036
59    2024-03-08  2024-03-08 18:59:24.941      card  ANON-0000-0000-0037
60    2024-03-09  2024-03-09 11:49:37.292      cash                  NaN
61    2024-03-09  2024-03-09 12:05:15.559      card  ANON-0000-0000-0038
62    2024-03-09  2024-03-09 12:07:38.275      card  ANON-0000-0000-0039
63    2024-03-09  2024-03-09 12:09:47.714      card  ANON-0000-0000-0012
64    2024-03-09  2024-03-09 12:13:03.521      card  ANON-0000-0000-0040
65    2024-03-09  2024-03-09 12:14:26.458      card  ANON-0000-0000-0040
66    2024-03-09  2024-03-09 13:09:22.229      card  ANON-0000-0000-0041
67    2024-03-09  2024-03-09 13:41:06.167      card  ANON-0000-0000-0042
68    2024-03-09  2024-03-09 13:53:10.408      card  ANON-0000-0000-0043
69    2024-03-09  2024-03-09 13:54:36.828      card  ANON-0000-0000-0043
70    2024-03-09  2024-03-09 14:08:01.829      card  ANON-0000-0000-0009
71    2024-03-09  2024-03-09 14:26:52.873      card  ANON-0000-0000-0044
72    2024-03-09  2024-03-09 19:17:57.572      card  ANON-0000-0000-0009
73    2024-03-09  2024-03-09 19:19:10.084      card  ANON-0000-0000-0009
74    2024-03-10  2024-03-10 07:44:18.538      cash                  NaN
75    2024-03-10  2024-03-10 07:45:29.441      cash                  NaN
76    2024-03-10  2024-03-10 10:06:02.960      cash                  NaN
77    2024-03-10  2024-03-10 11:19:20.764      card  ANON-0000-0000-0045
78    2024-03-10  2024-03-10 17:51:03.048      cash                  NaN
79    2024-03-10  2024-03-10 19:34:00.478      card  ANON-0000-0000-0046
80    2024-03-10  2024-03-10 19:35:54.712      card  ANON-0000-0000-0046
81    2024-03-11  2024-03-11 10:18:46.724      cash                  NaN
82    2024-03-11  2024-03-11 11:24:15.022      cash                  NaN
83    2024-03-11  2024-03-11 11:24:51.565      cash                  NaN
84    2024-03-11  2024-03-11 11:26:44.221      cash                  NaN
85    2024-03-11  2024-03-11 11:32:58.781      card  ANON-0000-0000-0035
86    2024-03-11  2024-03-11 16:24:26.401      card  ANON-0000-0000-0047
87    2024-03-11  2024-03-11 16:25:45.664      card  ANON-0000-0000-0047
88    2024-03-11  2024-03-11 16:50:49.608      card  ANON-0000-0000-0048
89    2024-03-12  2024-03-12 10:15:00.297      cash                  NaN
90    2024-03-12  2024-03-12 10:15:34.543      card  ANON-0000-0000-0033
91    2024-03-12  2024-03-12 10:16:24.886      card  ANON-0000-0000-0033
92    2024-03-12  2024-03-12 11:20:45.632      card  ANON-0000-0000-0049
93    2024-03-12  2024-03-12 12:46:23.275      card  ANON-0000-0000-0004
94    2024-03-12  2024-03-12 12:47:26.027      card  ANON-0000-0000-0004
95    2024-03-12  2024-03-12 16:15:43.325      card  ANON-0000-0000-0050
96    2024-03-13  2024-03-13 11:06:43.038      card  ANON-0000-0000-0048
97    2024-03-13  2024-03-13 11:48:16.753      card  ANON-0000-0000-0004
98    2024-03-13  2024-03-13 12:18:06.336      card  ANON-0000-0000-0051
99    2024-03-13  2024-03-13 12:19:05.128      card  ANON-0000-0000-0051
100   2024-03-13  2024-03-13 12:34:30.315      cash                  NaN
101   2024-03-13  2024-03-13 14:26:40.875      card  ANON-0000-0000-0052
102   2024-03-13  2024-03-13 15:40:22.261      card  ANON-0000-0000-0053
103   2024-03-13  2024-03-13 15:41:20.424      card  ANON-0000-0000-0053
104   2024-03-13  2024-03-13 16:47:09.373      card  ANON-0000-0000-0054
105   2024-03-14  2024-03-14 10:02:12.241      cash                  NaN
106   2024-03-14  2024-03-14 10:28:33.017      card  ANON-0000-0000-0055
107   2024-03-14  2024-03-14 10:29:34.283      card  ANON-0000-0000-0055
108   2024-03-14  2024-03-14 13:27:29.536      card  ANON-0000-0000-0012
109   2024-03-14  2024-03-14 13:28:24.527      card  ANON-0000-0000-0012
110   2024-03-14  2024-03-14 13:51:59.905      card  ANON-0000-0000-0056
111   2024-03-14  2024-03-14 13:52:56.248      card  ANON-0000-0000-0057
112   2024-03-14  2024-03-14 15:20:38.367      card  ANON-0000-0000-0058
113   2024-03-14  2024-03-14 16:04:09.506      card  ANON-0000-0000-0059
114   2024-03-14  2024-03-14 16:54:38.202      card  ANON-0000-0000-0050
115   2024-03-14  2024-03-14 18:58:55.854      card  ANON-0000-0000-0019
116   2024-03-14  2024-03-14 19:00:08.663      card  ANON-0000-0000-0012
117   2024-03-15  2024-03-15 10:02:16.533      cash                  NaN
118   2024-03-15  2024-03-15 10:53:02.180      card  ANON-0000-0000-0060
119   2024-03-15  2024-03-15 18:19:27.922      card  ANON-0000-0000-0012
120   2024-03-16  2024-03-16 12:06:55.209      card  ANON-0000-0000-0061
121   2024-03-16  2024-03-16 12:07:53.915      card  ANON-0000-0000-0061
122   2024-03-16  2024-03-16 15:58:18.458      card  ANON-0000-0000-0009
123   2024-03-16  2024-03-16 16:03:21.738      card  ANON-0000-0000-0009
124   2024-03-16  2024-03-16 16:04:11.444      card  ANON-0000-0000-0012
125   2024-03-16  2024-03-16 17:58:07.241      card  ANON-0000-0000-0062
126   2024-03-17  2024-03-17 10:10:21.399      cash                  NaN
127   2024-03-17  2024-03-17 12:55:26.065      card  ANON-0000-0000-0063
128   2024-03-18  2024-03-18 11:17:59.671      card  ANON-0000-0000-0064
129   2024-03-18  2024-03-18 15:31:39.725      card  ANON-0000-0000-0003
130   2024-03-18  2024-03-18 15:32:38.239      card  ANON-0000-0000-0003
131   2024-03-18  2024-03-18 15:33:36.708      card  ANON-0000-0000-0003
132   2024-03-19  2024-03-19 10:20:25.996      cash                  NaN
133   2024-03-19  2024-03-19 14:02:21.536      card  ANON-0000-0000-0065
134   2024-03-19  2024-03-19 14:03:19.765      card  ANON-0000-0000-0065
135   2024-03-19  2024-03-19 15:04:36.309      card  ANON-0000-0000-0049
136   2024-03-19  2024-03-19 16:53:48.706      card  ANON-0000-0000-0066
137   2024-03-19  2024-03-19 19:26:32.677      cash                  NaN
138   2024-03-20  2024-03-20 11:41:16.403      card  ANON-0000-0000-0012
139   2024-03-20  2024-03-20 12:21:07.728      cash                  NaN
140   2024-03-20  2024-03-20 12:30:48.968      card  ANON-0000-0000-0049
141   2024-03-20  2024-03-20 13:16:47.394      card  ANON-0000-0000-0067
142   2024-03-20  2024-03-20 16:42:38.117      card  ANON-0000-0000-0050
143   2024-03-20  2024-03-20 17:50:28.781      card  ANON-0000-0000-0068
144   2024-03-21  2024-03-21 10:18:56.977      cash                  NaN
145   2024-03-21  2024-03-21 12:25:09.194      card  ANON-0000-0000-0012
146   2024-03-21  2024-03-21 12:26:17.428      card  ANON-0000-0000-0012
147   2024-03-21  2024-03-21 17:21:01.453      cash                  NaN
148   2024-03-21  2024-03-21 17:22:01.353      card  ANON-0000-0000-0012
149   2024-03-21  2024-03-21 19:20:36.508      card  ANON-0000-0000-0069
150   2024-03-22  2024-03-22 10:35:53.619      card  ANON-0000-0000-0070
151   2024-03-22  2024-03-22 13:29:20.343      card  ANON-0000-0000-0071
152   2024-03-22  2024-03-22 16:15:14.448      cash                  NaN
153   2024-03-22  2024-03-22 17:17:03.724      card  ANON-0000-0000-0012
154   2024-03-22  2024-03-22 17:17:58.991      card  ANON-0000-0000-0012
155   2024-03-22  2024-03-22 17:20:49.490      card  ANON-0000-0000-0050
156   2024-03-23  2024-03-23 10:43:59.559      card  ANON-0000-0000-0072
157   2024-03-23  2024-03-23 10:45:07.157      card  ANON-0000-0000-0073
158   2024-03-23  2024-03-23 13:10:07.661      card  ANON-0000-0000-0074
159   2024-03-23  2024-03-23 13:11:12.230      card  ANON-0000-0000-0074
160   2024-03-23  2024-03-23 14:44:41.276      card  ANON-0000-0000-0075
161   2024-03-23  2024-03-23 15:47:19.062      card  ANON-0000-0000-0076
162   2024-03-23  2024-03-23 15:49:33.813      card  ANON-0000-0000-0076
163   2024-03-23  2024-03-23 16:00:58.386      card  ANON-0000-0000-0009
164   2024-03-24  2024-03-24 10:03:56.005      cash                  NaN
165   2024-03-24  2024-03-24 18:45:08.397      card  ANON-0000-0000-0077
166   2024-03-25  2024-03-25 10:31:47.250      card  ANON-0000-0000-0009
167   2024-03-25  2024-03-25 11:16:25.671      cash                  NaN
168   2024-03-25  2024-03-25 14:27:09.163      card  ANON-0000-0000-0078
169   2024-03-25  2024-03-25 14:29:25.343      card  ANON-0000-0000-0017
170   2024-03-25  2024-03-25 18:37:30.650      card  ANON-0000-0000-0024
171   2024-03-25  2024-03-25 19:34:24.542      card  ANON-0000-0000-0079
172   2024-03-26  2024-03-26 10:35:49.679      card  ANON-0000-0000-0055
173   2024-03-26  2024-03-26 10:36:36.151      card  ANON-0000-0000-0055
174   2024-03-26  2024-03-26 10:42:30.170      card  ANON-0000-0000-0080
175   2024-03-26  2024-03-26 11:11:47.335      card  ANON-0000-0000-0009
176   2024-03-26  2024-03-26 13:35:52.773      card  ANON-0000-0000-0003
177   2024-03-26  2024-03-26 13:36:49.644      card  ANON-0000-0000-0032
178   2024-03-26  2024-03-26 13:37:59.723      card  ANON-0000-0000-0059
179   2024-03-26  2024-03-26 13:57:53.677      card  ANON-0000-0000-0050
180   2024-03-26  2024-03-26 15:48:02.270      card  ANON-0000-0000-0081
181   2024-03-26  2024-03-26 18:33:38.568      card  ANON-0000-0000-0024
182   2024-03-26  2024-03-26 18:34:54.648      card  ANON-0000-0000-0009
183   2024-03-27  2024-03-27 11:04:51.174      card  ANON-0000-0000-0003
184   2024-03-27  2024-03-27 11:05:58.236      card  ANON-0000-0000-0003
185   2024-03-27  2024-03-27 12:57:00.462      card  ANON-0000-0000-0082
186   2024-03-27  2024-03-27 13:35:20.039      card  ANON-0000-0000-0083
187   2024-03-27  2024-03-27 14:22:31.662      card  ANON-0000-0000-0012
188   2024-03-27  2024-03-27 14:23:35.380      card  ANON-0000-0000-0012
189   2024-03-27  2024-03-27 18:30:11.833      card  ANON-0000-0000-0084
190   2024-03-27  2024-03-27 19:31:12.442      cash                  NaN
191   2024-03-28  2024-03-28 14:24:47.092      card  ANON-0000-0000-0085
192   2024-03-28  2024-03-28 17:24:46.244      card  ANON-0000-0000-0012
193   2024-03-28  2024-03-28 17:27:05.304      card  ANON-0000-0000-0012
194   2024-03-28  2024-03-28 17:32:44.652      card  ANON-0000-0000-0086
195   2024-03-29  2024-03-29 10:56:19.495      card  ANON-0000-0000-0087
196   2024-03-29  2024-03-29 12:34:17.383      card  ANON-0000-0000-0088
197   2024-03-29  2024-03-29 12:41:32.125      card  ANON-0000-0000-0088
198   2024-03-29  2024-03-29 13:22:44.618      cash                  NaN
199   2024-03-30  2024-03-30 11:59:19.854      card  ANON-0000-0000-0069
200   2024-03-30  2024-03-30 13:49:25.815      cash                  NaN
201   2024-03-30  2024-03-30 16:12:31.786      card  ANON-0000-0000-0017
202   2024-03-30  2024-03-30 16:36:40.513      card  ANON-0000-0000-0009
203   2024-03-30  2024-03-30 16:37:57.553      card  ANON-0000-0000-0009
204   2024-03-31  2024-03-31 10:40:04.523      card  ANON-0000-0000-0089
205   2024-03-31  2024-03-31 19:36:45.000      cash                  NaN
206   2024-04-01  2024-04-01 10:28:47.601      card  ANON-0000-0000-0004
207   2024-04-01  2024-04-01 10:29:42.318      card  ANON-0000-0000-0004
208   2024-04-01  2024-04-01 10:30:43.735      card  ANON-0000-0000-0004
209   2024-04-01  2024-04-01 11:15:43.836      card  ANON-0000-0000-0009
210   2024-04-01  2024-04-01 17:01:42.924      cash                  NaN
211   2024-04-01  2024-04-01 18:18:42.372      card  ANON-0000-0000-0024
212   2024-04-01  2024-04-01 18:45:27.436      card  ANON-0000-0000-0090
213   2024-04-02  2024-04-02 10:01:14.022      card  ANON-0000-0000-0001
214   2024-04-02  2024-04-02 16:18:34.169      card  ANON-0000-0000-0003
215   2024-04-02  2024-04-02 16:19:28.460      card  ANON-0000-0000-0003
216   2024-04-02  2024-04-02 19:59:31.942      cash                  NaN
217   2024-04-03  2024-04-03 10:19:13.644      card  ANON-0000-0000-0003
218   2024-04-03  2024-04-03 10:20:07.655      card  ANON-0000-0000-0003
219   2024-04-03  2024-04-03 13:12:05.367      card  ANON-0000-0000-0012
220   2024-04-03  2024-04-03 15:36:11.735      cash                  NaN
221   2024-04-04  2024-04-04 10:44:55.988      card  ANON-0000-0000-0091
222   2024-04-04  2024-04-04 11:26:38.085      card  ANON-0000-0000-0092
223   2024-04-04  2024-04-04 11:27:48.411      card  ANON-0000-0000-0093
224   2024-04-04  2024-04-04 12:23:02.216      card  ANON-0000-0000-0094
225   2024-04-04  2024-04-04 19:42:07.740      cash                  NaN
226   2024-04-05  2024-04-05 10:40:42.728      card  ANON-0000-0000-0095
227   2024-04-05  2024-04-05 10:42:06.204      card  ANON-0000-0000-0012
228   2024-04-05  2024-04-05 11:06:14.643      card  ANON-0000-0000-0096
229   2024-04-05  2024-04-05 12:14:27.975      card  ANON-0000-0000-0097
230   2024-04-05  2024-04-05 14:23:40.387      card  ANON-0000-0000-0098
231   2024-04-05  2024-04-05 14:24:50.417      card  ANON-0000-0000-0098
232   2024-04-05  2024-04-05 15:30:50.383      cash                  NaN
233   2024-04-05  2024-04-05 15:54:15.768      cash                  NaN
234   2024-04-05  2024-04-05 15:55:30.947      cash                  NaN
235   2024-04-05  2024-04-05 16:17:43.975      cash                  NaN
236   2024-04-05  2024-04-05 16:18:23.558      card  ANON-0000-0000-0003
237   2024-04-06  2024-04-06 12:32:31.398      card  ANON-0000-0000-0099
238   2024-04-06  2024-04-06 14:13:18.733      card  ANON-0000-0000-0040
239   2024-04-06  2024-04-06 14:14:27.029      card  ANON-0000-0000-0040
240   2024-04-06  2024-04-06 14:49:50.183      card  ANON-0000-0000-0009
241   2024-04-07  2024-04-07 10:12:53.204      card  ANON-0000-0000-0091
242   2024-04-07  2024-04-07 12:44:31.936      card  ANON-0000-0000-0040
243   2024-04-07  2024-04-07 12:46:05.118      card  ANON-0000-0000-0040
244   2024-04-07  2024-04-07 14:16:24.949      card  ANON-0000-0000-0100
245   2024-04-07  2024-04-07 14:17:30.628      card  ANON-0000-0000-0100
246   2024-04-07  2024-04-07 18:01:16.608      card  ANON-0000-0000-0101
247   2024-04-07  2024-04-07 18:02:03.878      card  ANON-0000-0000-0101
248   2024-04-08  2024-04-08 10:58:21.106      card  ANON-0000-0000-0102
249   2024-04-08  2024-04-08 10:59:27.558      card  ANON-0000-0000-0103
250   2024-04-08  2024-04-08 11:01:20.464      card  ANON-0000-0000-0012
251   2024-04-08  2024-04-08 11:04:47.030      card  ANON-0000-0000-0104
252   2024-04-08  2024-04-08 12:54:25.897      cash                  NaN
253   2024-04-08  2024-04-08 15:43:36.881      cash                  NaN
254   2024-04-08  2024-04-08 16:41:37.806      card  ANON-0000-0000-0017
255   2024-04-08  2024-04-08 18:18:09.713      card  ANON-0000-0000-0105
256   2024-04-08  2024-04-08 19:22:27.477      card  ANON-0000-0000-0024
257   2024-04-08  2024-04-08 19:23:59.268      card  ANON-0000-0000-0106
258   2024-04-09  2024-04-09 10:22:27.359      cash                  NaN
259   2024-04-09  2024-04-09 10:24:10.103      cash                  NaN
260   2024-04-09  2024-04-09 11:42:28.468      card  ANON-0000-0000-0091
261   2024-04-09  2024-04-09 15:11:48.720      card  ANON-0000-0000-0107
262   2024-04-09  2024-04-09 17:25:23.936      card  ANON-0000-0000-0049
263   2024-04-10  2024-04-10 10:21:26.175      cash                  NaN
264   2024-04-10  2024-04-10 17:55:07.018      cash                  NaN
265   2024-04-10  2024-04-10 17:55:31.244      card  ANON-0000-0000-0108
266   2024-04-10  2024-04-10 18:24:59.290      card  ANON-0000-0000-0009
267   2024-04-10  2024-04-10 20:04:05.386      card  ANON-0000-0000-0109
268   2024-04-11  2024-04-11 10:41:23.155      card  ANON-0000-0000-0110
269   2024-04-11  2024-04-11 10:42:59.365      card  ANON-0000-0000-0110
270   2024-04-11  2024-04-11 16:35:23.069      card  ANON-0000-0000-0017
271   2024-04-11  2024-04-11 19:16:56.588      card  ANON-0000-0000-0106

In [18]:
# fill the missing values in card column

In [19]:
data['card']=data['card'].fillna("payement in cash ")

In [20]:
data

            date                 datetime cash_type                 card  \
0     2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001
1     2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002
2     2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002
3     2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003
4     2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004
5     2024-03-01  2024-03-01 15:39:47.726      card  ANON-0000-0000-0005
6     2024-03-01  2024-03-01 16:19:02.756      card  ANON-0000-0000-0006
7     2024-03-01  2024-03-01 18:39:03.580      card  ANON-0000-0000-0007
8     2024-03-01  2024-03-01 19:22:01.762      card  ANON-0000-0000-0008
9     2024-03-01  2024-03-01 19:23:15.887      card  ANON-0000-0000-0008
10    2024-03-01  2024-03-01 19:29:17.391      card  ANON-0000-0000-0009
11    2024-03-02  2024-03-02 10:22:06.957      card  ANON-0000-0000-0010
12    2024-03-02  2024-03-02 10:30:35.668      cash    payement in cash
13    2024-03-02  2024-03-02 10:41:41.249      card  ANON-0000-0000-0011
14    2024-03-02  2024-03-02 11:59:45.484      card  ANON-0000-0000-0012
15    2024-03-02  2024-03-02 14:38:35.535      card  ANON-0000-0000-0013
16    2024-03-02  2024-03-02 16:37:24.475      card  ANON-0000-0000-0014
17    2024-03-02  2024-03-02 17:34:54.969      card  ANON-0000-0000-0004
18    2024-03-03  2024-03-03 10:10:43.981      cash    payement in cash
19    2024-03-03  2024-03-03 10:27:18.561      card  ANON-0000-0000-0015
20    2024-03-03  2024-03-03 11:33:56.118      card  ANON-0000-0000-0016
21    2024-03-03  2024-03-03 12:26:56.098      card  ANON-0000-0000-0012
22    2024-03-03  2024-03-03 13:09:36.321      card  ANON-0000-0000-0017
23    2024-03-03  2024-03-03 17:06:40.271      card  ANON-0000-0000-0018
24    2024-03-03  2024-03-03 17:08:45.895      card  ANON-0000-0000-0019
25    2024-03-03  2024-03-03 18:03:23.369      card  ANON-0000-0000-0020
26    2024-03-03  2024-03-03 18:04:27.946      card  ANON-0000-0000-0020
27    2024-03-03  2024-03-03 18:08:04.959      card  ANON-0000-0000-0020
28    2024-03-04  2024-03-04 10:03:51.994      card  ANON-0000-0000-0001
29    2024-03-04  2024-03-04 10:54:50.958      card  ANON-0000-0000-0021
30    2024-03-04  2024-03-04 11:05:16.184      card  ANON-0000-0000-0012
31    2024-03-04  2024-03-04 14:04:37.734      card  ANON-0000-0000-0022
32    2024-03-05  2024-03-05 09:59:52.651      card  ANON-0000-0000-0001
33    2024-03-05  2024-03-05 14:34:55.963      card  ANON-0000-0000-0023
34    2024-03-05  2024-03-05 17:34:06.043      card  ANON-0000-0000-0024
35    2024-03-05  2024-03-05 17:35:25.021      card  ANON-0000-0000-0025
36    2024-03-05  2024-03-05 17:36:28.571      card  ANON-0000-0000-0026
37    2024-03-05  2024-03-05 17:37:13.659      card  ANON-0000-0000-0027
38    2024-03-05  2024-03-05 17:38:09.354      card  ANON-0000-0000-0009
39    2024-03-05  2024-03-05 17:56:15.776      card  ANON-0000-0000-0028
40    2024-03-05  2024-03-05 18:01:31.242      card  ANON-0000-0000-0028
41    2024-03-06  2024-03-06 12:30:27.089      cash    payement in cash
42    2024-03-06  2024-03-06 13:24:07.667      card  ANON-0000-0000-0012
43    2024-03-06  2024-03-06 13:25:14.351      card  ANON-0000-0000-0012
44    2024-03-06  2024-03-06 14:52:01.761      card  ANON-0000-0000-0029
45    2024-03-06  2024-03-06 14:53:18.344      card  ANON-0000-0000-0029
46    2024-03-07  2024-03-07 10:08:58.945      cash    payement in cash
47    2024-03-07  2024-03-07 10:18:40.543      card  ANON-0000-0000-0030
48    2024-03-07  2024-03-07 11:03:58.976      card  ANON-0000-0000-0031
49    2024-03-07  2024-03-07 11:25:43.977      cash    payement in cash
50    2024-03-07  2024-03-07 15:40:22.606      card  ANON-0000-0000-0032
51    2024-03-07  2024-03-07 15:41:28.784      card  ANON-0000-0000-0033
52    2024-03-08  2024-03-08 10:34:41.283      card  ANON-0000-0000-0012
53    2024-03-08  2024-03-08 12:22:28.653      card  ANON-0000-0000-0034
54    2024-03-08  2024-03-08 13:53:02.042      card  ANON-0000-0000-0035
55    2024-03-08  2024-03-08 14:44:12.686      card  ANON-0000-0000-0012
56    2024-03-08  2024-03-08 14:45:11.048      card  ANON-0000-0000-0033
57    2024-03-08  2024-03-08 14:46:11.155      card  ANON-0000-0000-0012
58    2024-03-08  2024-03-08 18:57:51.451      card  ANON-0000-0000-0036
59    2024-03-08  2024-03-08 18:59:24.941      card  ANON-0000-0000-0037
60    2024-03-09  2024-03-09 11:49:37.292      cash    payement in cash
61    2024-03-09  2024-03-09 12:05:15.559      card  ANON-0000-0000-0038
62    2024-03-09  2024-03-09 12:07:38.275      card  ANON-0000-0000-0039
63    2024-03-09  2024-03-09 12:09:47.714      card  ANON-0000-0000-0012
64    2024-03-09  2024-03-09 12:13:03.521      card  ANON-0000-0000-0040
65    2024-03-09  2024-03-09 12:14:26.458      card  ANON-0000-0000-0040
66    2024-03-09  2024-03-09 13:09:22.229      card  ANON-0000-0000-0041
67    2024-03-09  2024-03-09 13:41:06.167      card  ANON-0000-0000-0042
68    2024-03-09  2024-03-09 13:53:10.408      card  ANON-0000-0000-0043
69    2024-03-09  2024-03-09 13:54:36.828      card  ANON-0000-0000-0043
70    2024-03-09  2024-03-09 14:08:01.829      card  ANON-0000-0000-0009
71    2024-03-09  2024-03-09 14:26:52.873      card  ANON-0000-0000-0044
72    2024-03-09  2024-03-09 19:17:57.572      card  ANON-0000-0000-0009
73    2024-03-09  2024-03-09 19:19:10.084      card  ANON-0000-0000-0009
74    2024-03-10  2024-03-10 07:44:18.538      cash    payement in cash
75    2024-03-10  2024-03-10 07:45:29.441      cash    payement in cash
76    2024-03-10  2024-03-10 10:06:02.960      cash    payement in cash
77    2024-03-10  2024-03-10 11:19:20.764      card  ANON-0000-0000-0045
78    2024-03-10  2024-03-10 17:51:03.048      cash    payement in cash
79    2024-03-10  2024-03-10 19:34:00.478      card  ANON-0000-0000-0046
80    2024-03-10  2024-03-10 19:35:54.712      card  ANON-0000-0000-0046
81    2024-03-11  2024-03-11 10:18:46.724      cash    payement in cash
82    2024-03-11  2024-03-11 11:24:15.022      cash    payement in cash
83    2024-03-11  2024-03-11 11:24:51.565      cash    payement in cash
84    2024-03-11  2024-03-11 11:26:44.221      cash    payement in cash
85    2024-03-11  2024-03-11 11:32:58.781      card  ANON-0000-0000-0035
86    2024-03-11  2024-03-11 16:24:26.401      card  ANON-0000-0000-0047
87    2024-03-11  2024-03-11 16:25:45.664      card  ANON-0000-0000-0047
88    2024-03-11  2024-03-11 16:50:49.608      card  ANON-0000-0000-0048
89    2024-03-12  2024-03-12 10:15:00.297      cash    payement in cash
90    2024-03-12  2024-03-12 10:15:34.543      card  ANON-0000-0000-0033
91    2024-03-12  2024-03-12 10:16:24.886      card  ANON-0000-0000-0033
92    2024-03-12  2024-03-12 11:20:45.632      card  ANON-0000-0000-0049
93    2024-03-12  2024-03-12 12:46:23.275      card  ANON-0000-0000-0004
94    2024-03-12  2024-03-12 12:47:26.027      card  ANON-0000-0000-0004
95    2024-03-12  2024-03-12 16:15:43.325      card  ANON-0000-0000-0050
96    2024-03-13  2024-03-13 11:06:43.038      card  ANON-0000-0000-0048
97    2024-03-13  2024-03-13 11:48:16.753      card  ANON-0000-0000-0004
98    2024-03-13  2024-03-13 12:18:06.336      card  ANON-0000-0000-0051
99    2024-03-13  2024-03-13 12:19:05.128      card  ANON-0000-0000-0051
100   2024-03-13  2024-03-13 12:34:30.315      cash    payement in cash
101   2024-03-13  2024-03-13 14:26:40.875      card  ANON-0000-0000-0052
102   2024-03-13  2024-03-13 15:40:22.261      card  ANON-0000-0000-0053
103   2024-03-13  2024-03-13 15:41:20.424      card  ANON-0000-0000-0053
104   2024-03-13  2024-03-13 16:47:09.373      card  ANON-0000-0000-0054
105   2024-03-14  2024-03-14 10:02:12.241      cash    payement in cash
106   2024-03-14  2024-03-14 10:28:33.017      card  ANON-0000-0000-0055
107   2024-03-14  2024-03-14 10:29:34.283      card  ANON-0000-0000-0055
108   2024-03-14  2024-03-14 13:27:29.536      card  ANON-0000-0000-0012
109   2024-03-14  2024-03-14 13:28:24.527      card  ANON-0000-0000-0012
110   2024-03-14  2024-03-14 13:51:59.905      card  ANON-0000-0000-0056
111   2024-03-14  2024-03-14 13:52:56.248      card  ANON-0000-0000-0057
112   2024-03-14  2024-03-14 15:20:38.367      card  ANON-0000-0000-0058
113   2024-03-14  2024-03-14 16:04:09.506      card  ANON-0000-0000-0059
114   2024-03-14  2024-03-14 16:54:38.202      card  ANON-0000-0000-0050
115   2024-03-14  2024-03-14 18:58:55.854      card  ANON-0000-0000-0019
116   2024-03-14  2024-03-14 19:00:08.663      card  ANON-0000-0000-0012
117   2024-03-15  2024-03-15 10:02:16.533      cash    payement in cash
118   2024-03-15  2024-03-15 10:53:02.180      card  ANON-0000-0000-0060
119   2024-03-15  2024-03-15 18:19:27.922      card  ANON-0000-0000-0012
120   2024-03-16  2024-03-16 12:06:55.209      card  ANON-0000-0000-0061
121   2024-03-16  2024-03-16 12:07:53.915      card  ANON-0000-0000-0061
122   2024-03-16  2024-03-16 15:58:18.458      card  ANON-0000-0000-0009
123   2024-03-16  2024-03-16 16:03:21.738      card  ANON-0000-0000-0009
124   2024-03-16  2024-03-16 16:04:11.444      card  ANON-0000-0000-0012
125   2024-03-16  2024-03-16 17:58:07.241      card  ANON-0000-0000-0062
126   2024-03-17  2024-03-17 10:10:21.399      cash    payement in cash
127   2024-03-17  2024-03-17 12:55:26.065      card  ANON-0000-0000-0063
128   2024-03-18  2024-03-18 11:17:59.671      card  ANON-0000-0000-0064
129   2024-03-18  2024-03-18 15:31:39.725      card  ANON-0000-0000-0003
130   2024-03-18  2024-03-18 15:32:38.239      card  ANON-0000-0000-0003
131   2024-03-18  2024-03-18 15:33:36.708      card  ANON-0000-0000-0003
132   2024-03-19  2024-03-19 10:20:25.996      cash    payement in cash
133   2024-03-19  2024-03-19 14:02:21.536      card  ANON-0000-0000-0065
134   2024-03-19  2024-03-19 14:03:19.765      card  ANON-0000-0000-0065
135   2024-03-19  2024-03-19 15:04:36.309      card  ANON-0000-0000-0049
136   2024-03-19  2024-03-19 16:53:48.706      card  ANON-0000-0000-0066
137   2024-03-19  2024-03-19 19:26:32.677      cash    payement in cash
138   2024-03-20  2024-03-20 11:41:16.403      card  ANON-0000-0000-0012
139   2024-03-20  2024-03-20 12:21:07.728      cash    payement in cash
140   2024-03-20  2024-03-20 12:30:48.968      card  ANON-0000-0000-0049
141   2024-03-20  2024-03-20 13:16:47.394      card  ANON-0000-0000-0067
142   2024-03-20  2024-03-20 16:42:38.117      card  ANON-0000-0000-0050
143   2024-03-20  2024-03-20 17:50:28.781      card  ANON-0000-0000-0068
144   2024-03-21  2024-03-21 10:18:56.977      cash    payement in cash
145   2024-03-21  2024-03-21 12:25:09.194      card  ANON-0000-0000-0012
146   2024-03-21  2024-03-21 12:26:17.428      card  ANON-0000-0000-0012
147   2024-03-21  2024-03-21 17:21:01.453      cash    payement in cash
148   2024-03-21  2024-03-21 17:22:01.353      card  ANON-0000-0000-0012
149   2024-03-21  2024-03-21 19:20:36.508      card  ANON-0000-0000-0069
150   2024-03-22  2024-03-22 10:35:53.619      card  ANON-0000-0000-0070
151   2024-03-22  2024-03-22 13:29:20.343      card  ANON-0000-0000-0071
152   2024-03-22  2024-03-22 16:15:14.448      cash    payement in cash
153   2024-03-22  2024-03-22 17:17:03.724      card  ANON-0000-0000-0012
154   2024-03-22  2024-03-22 17:17:58.991      card  ANON-0000-0000-0012
155   2024-03-22  2024-03-22 17:20:49.490      card  ANON-0000-0000-0050
156   2024-03-23  2024-03-23 10:43:59.559      card  ANON-0000-0000-0072
157   2024-03-23  2024-03-23 10:45:07.157      card  ANON-0000-0000-0073
158   2024-03-23  2024-03-23 13:10:07.661      card  ANON-0000-0000-0074
159   2024-03-23  2024-03-23 13:11:12.230      card  ANON-0000-0000-0074
160   2024-03-23  2024-03-23 14:44:41.276      card  ANON-0000-0000-0075
161   2024-03-23  2024-03-23 15:47:19.062      card  ANON-0000-0000-0076
162   2024-03-23  2024-03-23 15:49:33.813      card  ANON-0000-0000-0076
163   2024-03-23  2024-03-23 16:00:58.386      card  ANON-0000-0000-0009
164   2024-03-24  2024-03-24 10:03:56.005      cash    payement in cash
165   2024-03-24  2024-03-24 18:45:08.397      card  ANON-0000-0000-0077
166   2024-03-25  2024-03-25 10:31:47.250      card  ANON-0000-0000-0009
167   2024-03-25  2024-03-25 11:16:25.671      cash    payement in cash
168   2024-03-25  2024-03-25 14:27:09.163      card  ANON-0000-0000-0078
169   2024-03-25  2024-03-25 14:29:25.343      card  ANON-0000-0000-0017
170   2024-03-25  2024-03-25 18:37:30.650      card  ANON-0000-0000-0024
171   2024-03-25  2024-03-25 19:34:24.542      card  ANON-0000-0000-0079
172   2024-03-26  2024-03-26 10:35:49.679      card  ANON-0000-0000-0055
173   2024-03-26  2024-03-26 10:36:36.151      card  ANON-0000-0000-0055
174   2024-03-26  2024-03-26 10:42:30.170      card  ANON-0000-0000-0080
175   2024-03-26  2024-03-26 11:11:47.335      card  ANON-0000-0000-0009
176   2024-03-26  2024-03-26 13:35:52.773      card  ANON-0000-0000-0003
177   2024-03-26  2024-03-26 13:36:49.644      card  ANON-0000-0000-0032
178   2024-03-26  2024-03-26 13:37:59.723      card  ANON-0000-0000-0059
179   2024-03-26  2024-03-26 13:57:53.677      card  ANON-0000-0000-0050
180   2024-03-26  2024-03-26 15:48:02.270      card  ANON-0000-0000-0081
181   2024-03-26  2024-03-26 18:33:38.568      card  ANON-0000-0000-0024
182   2024-03-26  2024-03-26 18:34:54.648      card  ANON-0000-0000-0009
183   2024-03-27  2024-03-27 11:04:51.174      card  ANON-0000-0000-0003
184   2024-03-27  2024-03-27 11:05:58.236      card  ANON-0000-0000-0003
185   2024-03-27  2024-03-27 12:57:00.462      card  ANON-0000-0000-0082
186   2024-03-27  2024-03-27 13:35:20.039      card  ANON-0000-0000-0083
187   2024-03-27  2024-03-27 14:22:31.662      card  ANON-0000-0000-0012
188   2024-03-27  2024-03-27 14:23:35.380      card  ANON-0000-0000-0012
189   2024-03-27  2024-03-27 18:30:11.833      card  ANON-0000-0000-0084
190   2024-03-27  2024-03-27 19:31:12.442      cash    payement in cash
191   2024-03-28  2024-03-28 14:24:47.092      card  ANON-0000-0000-0085
192   2024-03-28  2024-03-28 17:24:46.244      card  ANON-0000-0000-0012
193   2024-03-28  2024-03-28 17:27:05.304      card  ANON-0000-0000-0012
194   2024-03-28  2024-03-28 17:32:44.652      card  ANON-0000-0000-0086
195   2024-03-29  2024-03-29 10:56:19.495      card  ANON-0000-0000-0087
196   2024-03-29  2024-03-29 12:34:17.383      card  ANON-0000-0000-0088
197   2024-03-29  2024-03-29 12:41:32.125      card  ANON-0000-0000-0088
198   2024-03-29  2024-03-29 13:22:44.618      cash    payement in cash
199   2024-03-30  2024-03-30 11:59:19.854      card  ANON-0000-0000-0069
200   2024-03-30  2024-03-30 13:49:25.815      cash    payement in cash
201   2024-03-30  2024-03-30 16:12:31.786      card  ANON-0000-0000-0017
202   2024-03-30  2024-03-30 16:36:40.513      card  ANON-0000-0000-0009
203   2024-03-30  2024-03-30 16:37:57.553      card  ANON-0000-0000-0009
204   2024-03-31  2024-03-31 10:40:04.523      card  ANON-0000-0000-0089
205   2024-03-31  2024-03-31 19:36:45.000      cash    payement in cash
206   2024-04-01  2024-04-01 10:28:47.601      card  ANON-0000-0000-0004
207   2024-04-01  2024-04-01 10:29:42.318      card  ANON-0000-0000-0004
208   2024-04-01  2024-04-01 10:30:43.735      card  ANON-0000-0000-0004
209   2024-04-01  2024-04-01 11:15:43.836      card  ANON-0000-0000-0009
210   2024-04-01  2024-04-01 17:01:42.924      cash    payement in cash
211   2024-04-01  2024-04-01 18:18:42.372      card  ANON-0000-0000-0024
212   2024-04-01  2024-04-01 18:45:27.436      card  ANON-0000-0000-0090
213   2024-04-02  2024-04-02 10:01:14.022      card  ANON-0000-0000-0001
214   2024-04-02  2024-04-02 16:18:34.169      card  ANON-0000-0000-0003
215   2024-04-02  2024-04-02 16:19:28.460      card  ANON-0000-0000-0003
216   2024-04-02  2024-04-02 19:59:31.942      cash    payement in cash
217   2024-04-03  2024-04-03 10:19:13.644      card  ANON-0000-0000-0003
218   2024-04-03  2024-04-03 10:20:07.655      card  ANON-0000-0000-0003
219   2024-04-03  2024-04-03 13:12:05.367      card  ANON-0000-0000-0012
220   2024-04-03  2024-04-03 15:36:11.735      cash    payement in cash
221   2024-04-04  2024-04-04 10:44:55.988      card  ANON-0000-0000-0091
222   2024-04-04  2024-04-04 11:26:38.085      card  ANON-0000-0000-0092
223   2024-04-04  2024-04-04 11:27:48.411      card  ANON-0000-0000-0093
224   2024-04-04  2024-04-04 12:23:02.216      card  ANON-0000-0000-0094
225   2024-04-04  2024-04-04 19:42:07.740      cash    payement in cash
226   2024-04-05  2024-04-05 10:40:42.728      card  ANON-0000-0000-0095
227   2024-04-05  2024-04-05 10:42:06.204      card  ANON-0000-0000-0012
228   2024-04-05  2024-04-05 11:06:14.643      card  ANON-0000-0000-0096
229   2024-04-05  2024-04-05 12:14:27.975      card  ANON-0000-0000-0097
230   2024-04-05  2024-04-05 14:23:40.387      card  ANON-0000-0000-0098
231   2024-04-05  2024-04-05 14:24:50.417      card  ANON-0000-0000-0098
232   2024-04-05  2024-04-05 15:30:50.383      cash    payement in cash
233   2024-04-05  2024-04-05 15:54:15.768      cash    payement in cash
234   2024-04-05  2024-04-05 15:55:30.947      cash    payement in cash
235   2024-04-05  2024-04-05 16:17:43.975      cash    payement in cash
236   2024-04-05  2024-04-05 16:18:23.558      card  ANON-0000-0000-0003
237   2024-04-06  2024-04-06 12:32:31.398      card  ANON-0000-0000-0099
238   2024-04-06  2024-04-06 14:13:18.733      card  ANON-0000-0000-0040
239   2024-04-06  2024-04-06 14:14:27.029      card  ANON-0000-0000-0040
240   2024-04-06  2024-04-06 14:49:50.183      card  ANON-0000-0000-0009
241   2024-04-07  2024-04-07 10:12:53.204      card  ANON-0000-0000-0091
242   2024-04-07  2024-04-07 12:44:31.936      card  ANON-0000-0000-0040
243   2024-04-07  2024-04-07 12:46:05.118      card  ANON-0000-0000-0040
244   2024-04-07  2024-04-07 14:16:24.949      card  ANON-0000-0000-0100
245   2024-04-07  2024-04-07 14:17:30.628      card  ANON-0000-0000-0100
246   2024-04-07  2024-04-07 18:01:16.608      card  ANON-0000-0000-0101
247   2024-04-07  2024-04-07 18:02:03.878      card  ANON-0000-0000-0101
248   2024-04-08  2024-04-08 10:58:21.106      card  ANON-0000-0000-0102
249   2024-04-08  2024-04-08 10:59:27.558      card  ANON-0000-0000-0103
250   2024-04-08  2024-04-08 11:01:20.464      card  ANON-0000-0000-0012
251   2024-04-08  2024-04-08 11:04:47.030      card  ANON-0000-0000-0104
252   2024-04-08  2024-04-08 12:54:25.897      cash    payement in cash
253   2024-04-08  2024-04-08 15:43:36.881      cash    payement in cash
254   2024-04-08  2024-04-08 16:41:37.806      card  ANON-0000-0000-0017
255   2024-04-08  2024-04-08 18:18:09.713      card  ANON-0000-0000-0105
256   2024-04-08  2024-04-08 19:22:27.477      card  ANON-0000-0000-0024
257   2024-04-08  2024-04-08 19:23:59.268      card  ANON-0000-0000-0106
258   2024-04-09  2024-04-09 10:22:27.359      cash    payement in cash
259   2024-04-09  2024-04-09 10:24:10.103      cash    payement in cash
260   2024-04-09  2024-04-09 11:42:28.468      card  ANON-0000-0000-0091
261   2024-04-09  2024-04-09 15:11:48.720      card  ANON-0000-0000-0107
262   2024-04-09  2024-04-09 17:25:23.936      card  ANON-0000-0000-0049
263   2024-04-10  2024-04-10 10:21:26.175      cash    payement in cash
264   2024-04-10  2024-04-10 17:55:07.018      cash    payement in cash
265   2024-04-10  2024-04-10 17:55:31.244      card  ANON-0000-0000-0108
266   2024-04-10  2024-04-10 18:24:59.290      card  ANON-0000-0000-0009
267   2024-04-10  2024-04-10 20:04:05.386      card  ANON-0000-0000-0109
268   2024-04-11  2024-04-11 10:41:23.155      card  ANON-0000-0000-0110
269   2024-04-11  2024-04-11 10:42:59.365      card  ANON-0000-0000-0110
270   2024-04-11  2024-04-11 16:35:23.069      card  ANON-0000-0000-0017
271   2024-04-11  2024-04-11 19:16:56.588      card  ANON-0000-0000-0106
272   2024-04-11  2024-04-11 19:18:36.619      card  ANON-0000-0000-0024

In [21]:
# data duplicate

In [22]:
data.duplicated().sum()

np.int64(0)

In [23]:
data[data.duplicated()]

Empty DataFrame
Columns: [date, datetime, cash_type, card, money, coffee_name]
Index: []

In [24]:
# to check duplicate for specific column

In [28]:
data[data.duplicated(subset=["card"] , keep=False)]

            date                 datetime cash_type                 card  \
0     2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001
1     2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002
2     2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002
3     2024-03-01  2024-03-01 13:46:33.006      card  ANON-0000-0000-0003
4     2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004
8     2024-03-01  2024-03-01 19:22:01.762      card  ANON-0000-0000-0008
9     2024-03-01  2024-03-01 19:23:15.887      card  ANON-0000-0000-0008
10    2024-03-01  2024-03-01 19:29:17.391      card  ANON-0000-0000-0009
12    2024-03-02  2024-03-02 10:30:35.668      cash    payement in cash
14    2024-03-02  2024-03-02 11:59:45.484      card  ANON-0000-0000-0012
17    2024-03-02  2024-03-02 17:34:54.969      card  ANON-0000-0000-0004
18    2024-03-03  2024-03-03 10:10:43.981      cash    payement in cash
21    2024-03-03  2024-03-03 12:26:56.098      card  ANON-0000-0000-0012
22    2024-03-03  2024-03-03 13:09:36.321      card  ANON-0000-0000-0017
24    2024-03-03  2024-03-03 17:08:45.895      card  ANON-0000-0000-0019
25    2024-03-03  2024-03-03 18:03:23.369      card  ANON-0000-0000-0020
26    2024-03-03  2024-03-03 18:04:27.946      card  ANON-0000-0000-0020
27    2024-03-03  2024-03-03 18:08:04.959      card  ANON-0000-0000-0020
28    2024-03-04  2024-03-04 10:03:51.994      card  ANON-0000-0000-0001
30    2024-03-04  2024-03-04 11:05:16.184      card  ANON-0000-0000-0012
32    2024-03-05  2024-03-05 09:59:52.651      card  ANON-0000-0000-0001
34    2024-03-05  2024-03-05 17:34:06.043      card  ANON-0000-0000-0024
35    2024-03-05  2024-03-05 17:35:25.021      card  ANON-0000-0000-0025
36    2024-03-05  2024-03-05 17:36:28.571      card  ANON-0000-0000-0026
38    2024-03-05  2024-03-05 17:38:09.354      card  ANON-0000-0000-0009
39    2024-03-05  2024-03-05 17:56:15.776      card  ANON-0000-0000-0028
40    2024-03-05  2024-03-05 18:01:31.242      card  ANON-0000-0000-0028
41    2024-03-06  2024-03-06 12:30:27.089      cash    payement in cash
42    2024-03-06  2024-03-06 13:24:07.667      card  ANON-0000-0000-0012
43    2024-03-06  2024-03-06 13:25:14.351      card  ANON-0000-0000-0012
44    2024-03-06  2024-03-06 14:52:01.761      card  ANON-0000-0000-0029
45    2024-03-06  2024-03-06 14:53:18.344      card  ANON-0000-0000-0029
46    2024-03-07  2024-03-07 10:08:58.945      cash    payement in cash
49    2024-03-07  2024-03-07 11:25:43.977      cash    payement in cash
50    2024-03-07  2024-03-07 15:40:22.606      card  ANON-0000-0000-0032
51    2024-03-07  2024-03-07 15:41:28.784      card  ANON-0000-0000-0033
52    2024-03-08  2024-03-08 10:34:41.283      card  ANON-0000-0000-0012
54    2024-03-08  2024-03-08 13:53:02.042      card  ANON-0000-0000-0035
55    2024-03-08  2024-03-08 14:44:12.686      card  ANON-0000-0000-0012
56    2024-03-08  2024-03-08 14:45:11.048      card  ANON-0000-0000-0033
57    2024-03-08  2024-03-08 14:46:11.155      card  ANON-0000-0000-0012
60    2024-03-09  2024-03-09 11:49:37.292      cash    payement in cash
63    2024-03-09  2024-03-09 12:09:47.714      card  ANON-0000-0000-0012
64    2024-03-09  2024-03-09 12:13:03.521      card  ANON-0000-0000-0040
65    2024-03-09  2024-03-09 12:14:26.458      card  ANON-0000-0000-0040
67    2024-03-09  2024-03-09 13:41:06.167      card  ANON-0000-0000-0042
68    2024-03-09  2024-03-09 13:53:10.408      card  ANON-0000-0000-0043
69    2024-03-09  2024-03-09 13:54:36.828      card  ANON-0000-0000-0043
70    2024-03-09  2024-03-09 14:08:01.829      card  ANON-0000-0000-0009
72    2024-03-09  2024-03-09 19:17:57.572      card  ANON-0000-0000-0009
73    2024-03-09  2024-03-09 19:19:10.084      card  ANON-0000-0000-0009
74    2024-03-10  2024-03-10 07:44:18.538      cash    payement in cash
75    2024-03-10  2024-03-10 07:45:29.441      cash    payement in cash
76    2024-03-10  2024-03-10 10:06:02.960      cash    payement in cash
78    2024-03-10  2024-03-10 17:51:03.048      cash    payement in cash
79    2024-03-10  2024-03-10 19:34:00.478      card  ANON-0000-0000-0046
80    2024-03-10  2024-03-10 19:35:54.712      card  ANON-0000-0000-0046
81    2024-03-11  2024-03-11 10:18:46.724      cash    payement in cash
82    2024-03-11  2024-03-11 11:24:15.022      cash    payement in cash
83    2024-03-11  2024-03-11 11:24:51.565      cash    payement in cash
84    2024-03-11  2024-03-11 11:26:44.221      cash    payement in cash
85    2024-03-11  2024-03-11 11:32:58.781      card  ANON-0000-0000-0035
86    2024-03-11  2024-03-11 16:24:26.401      card  ANON-0000-0000-0047
87    2024-03-11  2024-03-11 16:25:45.664      card  ANON-0000-0000-0047
88    2024-03-11  2024-03-11 16:50:49.608      card  ANON-0000-0000-0048
89    2024-03-12  2024-03-12 10:15:00.297      cash    payement in cash
90    2024-03-12  2024-03-12 10:15:34.543      card  ANON-0000-0000-0033
91    2024-03-12  2024-03-12 10:16:24.886      card  ANON-0000-0000-0033
92    2024-03-12  2024-03-12 11:20:45.632      card  ANON-0000-0000-0049
93    2024-03-12  2024-03-12 12:46:23.275      card  ANON-0000-0000-0004
94    2024-03-12  2024-03-12 12:47:26.027      card  ANON-0000-0000-0004
95    2024-03-12  2024-03-12 16:15:43.325      card  ANON-0000-0000-0050
96    2024-03-13  2024-03-13 11:06:43.038      card  ANON-0000-0000-0048
97    2024-03-13  2024-03-13 11:48:16.753      card  ANON-0000-0000-0004
98    2024-03-13  2024-03-13 12:18:06.336      card  ANON-0000-0000-0051
99    2024-03-13  2024-03-13 12:19:05.128      card  ANON-0000-0000-0051
100   2024-03-13  2024-03-13 12:34:30.315      cash    payement in cash
102   2024-03-13  2024-03-13 15:40:22.261      card  ANON-0000-0000-0053
103   2024-03-13  2024-03-13 15:41:20.424      card  ANON-0000-0000-0053
104   2024-03-13  2024-03-13 16:47:09.373      card  ANON-0000-0000-0054
105   2024-03-14  2024-03-14 10:02:12.241      cash    payement in cash
106   2024-03-14  2024-03-14 10:28:33.017      card  ANON-0000-0000-0055
107   2024-03-14  2024-03-14 10:29:34.283      card  ANON-0000-0000-0055
108   2024-03-14  2024-03-14 13:27:29.536      card  ANON-0000-0000-0012
109   2024-03-14  2024-03-14 13:28:24.527      card  ANON-0000-0000-0012
112   2024-03-14  2024-03-14 15:20:38.367      card  ANON-0000-0000-0058
113   2024-03-14  2024-03-14 16:04:09.506      card  ANON-0000-0000-0059
114   2024-03-14  2024-03-14 16:54:38.202      card  ANON-0000-0000-0050
115   2024-03-14  2024-03-14 18:58:55.854      card  ANON-0000-0000-0019
116   2024-03-14  2024-03-14 19:00:08.663      card  ANON-0000-0000-0012
117   2024-03-15  2024-03-15 10:02:16.533      cash    payement in cash
119   2024-03-15  2024-03-15 18:19:27.922      card  ANON-0000-0000-0012
120   2024-03-16  2024-03-16 12:06:55.209      card  ANON-0000-0000-0061
121   2024-03-16  2024-03-16 12:07:53.915      card  ANON-0000-0000-0061
122   2024-03-16  2024-03-16 15:58:18.458      card  ANON-0000-0000-0009
123   2024-03-16  2024-03-16 16:03:21.738      card  ANON-0000-0000-0009
124   2024-03-16  2024-03-16 16:04:11.444      card  ANON-0000-0000-0012
126   2024-03-17  2024-03-17 10:10:21.399      cash    payement in cash
128   2024-03-18  2024-03-18 11:17:59.671      card  ANON-0000-0000-0064
129   2024-03-18  2024-03-18 15:31:39.725      card  ANON-0000-0000-0003
130   2024-03-18  2024-03-18 15:32:38.239      card  ANON-0000-0000-0003
131   2024-03-18  2024-03-18 15:33:36.708      card  ANON-0000-0000-0003
132   2024-03-19  2024-03-19 10:20:25.996      cash    payement in cash
133   2024-03-19  2024-03-19 14:02:21.536      card  ANON-0000-0000-0065
134   2024-03-19  2024-03-19 14:03:19.765      card  ANON-0000-0000-0065
135   2024-03-19  2024-03-19 15:04:36.309      card  ANON-0000-0000-0049
137   2024-03-19  2024-03-19 19:26:32.677      cash    payement in cash
138   2024-03-20  2024-03-20 11:41:16.403      card  ANON-0000-0000-0012
139   2024-03-20  2024-03-20 12:21:07.728      cash    payement in cash
140   2024-03-20  2024-03-20 12:30:48.968      card  ANON-0000-0000-0049
142   2024-03-20  2024-03-20 16:42:38.117      card  ANON-0000-0000-0050
144   2024-03-21  2024-03-21 10:18:56.977      cash    payement in cash
145   2024-03-21  2024-03-21 12:25:09.194      card  ANON-0000-0000-0012
146   2024-03-21  2024-03-21 12:26:17.428      card  ANON-0000-0000-0012
147   2024-03-21  2024-03-21 17:21:01.453      cash    payement in cash
148   2024-03-21  2024-03-21 17:22:01.353      card  ANON-0000-0000-0012
149   2024-03-21  2024-03-21 19:20:36.508      card  ANON-0000-0000-0069
152   2024-03-22  2024-03-22 16:15:14.448      cash    payement in cash
153   2024-03-22  2024-03-22 17:17:03.724      card  ANON-0000-0000-0012
154   2024-03-22  2024-03-22 17:17:58.991      card  ANON-0000-0000-0012
155   2024-03-22  2024-03-22 17:20:49.490      card  ANON-0000-0000-0050
158   2024-03-23  2024-03-23 13:10:07.661      card  ANON-0000-0000-0074
159   2024-03-23  2024-03-23 13:11:12.230      card  ANON-0000-0000-0074
161   2024-03-23  2024-03-23 15:47:19.062      card  ANON-0000-0000-0076
162   2024-03-23  2024-03-23 15:49:33.813      card  ANON-0000-0000-0076
163   2024-03-23  2024-03-23 16:00:58.386      card  ANON-0000-0000-0009
164   2024-03-24  2024-03-24 10:03:56.005      cash    payement in cash
165   2024-03-24  2024-03-24 18:45:08.397      card  ANON-0000-0000-0077
166   2024-03-25  2024-03-25 10:31:47.250      card  ANON-0000-0000-0009
167   2024-03-25  2024-03-25 11:16:25.671      cash    payement in cash
169   2024-03-25  2024-03-25 14:29:25.343      card  ANON-0000-0000-0017
170   2024-03-25  2024-03-25 18:37:30.650      card  ANON-0000-0000-0024
172   2024-03-26  2024-03-26 10:35:49.679      card  ANON-0000-0000-0055
173   2024-03-26  2024-03-26 10:36:36.151      card  ANON-0000-0000-0055
175   2024-03-26  2024-03-26 11:11:47.335      card  ANON-0000-0000-0009
176   2024-03-26  2024-03-26 13:35:52.773      card  ANON-0000-0000-0003
177   2024-03-26  2024-03-26 13:36:49.644      card  ANON-0000-0000-0032
178   2024-03-26  2024-03-26 13:37:59.723      card  ANON-0000-0000-0059
179   2024-03-26  2024-03-26 13:57:53.677      card  ANON-0000-0000-0050
180   2024-03-26  2024-03-26 15:48:02.270      card  ANON-0000-0000-0081
181   2024-03-26  2024-03-26 18:33:38.568      card  ANON-0000-0000-0024
182   2024-03-26  2024-03-26 18:34:54.648      card  ANON-0000-0000-0009
183   2024-03-27  2024-03-27 11:04:51.174      card  ANON-0000-0000-0003
184   2024-03-27  2024-03-27 11:05:58.236      card  ANON-0000-0000-0003
187   2024-03-27  2024-03-27 14:22:31.662      card  ANON-0000-0000-0012
188   2024-03-27  2024-03-27 14:23:35.380      card  ANON-0000-0000-0012
189   2024-03-27  2024-03-27 18:30:11.833      card  ANON-0000-0000-0084
190   2024-03-27  2024-03-27 19:31:12.442      cash    payement in cash
191   2024-03-28  2024-03-28 14:24:47.092      card  ANON-0000-0000-0085
192   2024-03-28  2024-03-28 17:24:46.244      card  ANON-0000-0000-0012
193   2024-03-28  2024-03-28 17:27:05.304      card  ANON-0000-0000-0012
196   2024-03-29  2024-03-29 12:34:17.383      card  ANON-0000-0000-0088
197   2024-03-29  2024-03-29 12:41:32.125      card  ANON-0000-0000-0088
198   2024-03-29  2024-03-29 13:22:44.618      cash    payement in cash
199   2024-03-30  2024-03-30 11:59:19.854      card  ANON-0000-0000-0069
200   2024-03-30  2024-03-30 13:49:25.815      cash    payement in cash
201   2024-03-30  2024-03-30 16:12:31.786      card  ANON-0000-0000-0017
202   2024-03-30  2024-03-30 16:36:40.513      card  ANON-0000-0000-0009
203   2024-03-30  2024-03-30 16:37:57.553      card  ANON-0000-0000-0009
205   2024-03-31  2024-03-31 19:36:45.000      cash    payement in cash
206   2024-04-01  2024-04-01 10:28:47.601      card  ANON-0000-0000-0004
207   2024-04-01  2024-04-01 10:29:42.318      card  ANON-0000-0000-0004
208   2024-04-01  2024-04-01 10:30:43.735      card  ANON-0000-0000-0004
209   2024-04-01  2024-04-01 11:15:43.836      card  ANON-0000-0000-0009
210   2024-04-01  2024-04-01 17:01:42.924      cash    payement in cash
211   2024-04-01  2024-04-01 18:18:42.372      card  ANON-0000-0000-0024
213   2024-04-02  2024-04-02 10:01:14.022      card  ANON-0000-0000-0001
214   2024-04-02  2024-04-02 16:18:34.169      card  ANON-0000-0000-0003
215   2024-04-02  2024-04-02 16:19:28.460      card  ANON-0000-0000-0003
216   2024-04-02  2024-04-02 19:59:31.942      cash    payement in cash
217   2024-04-03  2024-04-03 10:19:13.644      card  ANON-0000-0000-0003
218   2024-04-03  2024-04-03 10:20:07.655      card  ANON-0000-0000-0003
219   2024-04-03  2024-04-03 13:12:05.367      card  ANON-0000-0000-0012
220   2024-04-03  2024-04-03 15:36:11.735      cash    payement in cash
221   2024-04-04  2024-04-04 10:44:55.988      card  ANON-0000-0000-0091
225   2024-04-04  2024-04-04 19:42:07.740      cash    payement in cash
226   2024-04-05  2024-04-05 10:40:42.728      card  ANON-0000-0000-0095
227   2024-04-05  2024-04-05 10:42:06.204      card  ANON-0000-0000-0012
229   2024-04-05  2024-04-05 12:14:27.975      card  ANON-0000-0000-0097
230   2024-04-05  2024-04-05 14:23:40.387      card  ANON-0000-0000-0098
231   2024-04-05  2024-04-05 14:24:50.417      card  ANON-0000-0000-0098
232   2024-04-05  2024-04-05 15:30:50.383      cash    payement in cash
233   2024-04-05  2024-04-05 15:54:15.768      cash    payement in cash
234   2024-04-05  2024-04-05 15:55:30.947      cash    payement in cash
235   2024-04-05  2024-04-05 16:17:43.975      cash    payement in cash
236   2024-04-05  2024-04-05 16:18:23.558      card  ANON-0000-0000-0003
237   2024-04-06  2024-04-06 12:32:31.398      card  ANON-0000-0000-0099
238   2024-04-06  2024-04-06 14:13:18.733      card  ANON-0000-0000-0040
239   2024-04-06  2024-04-06 14:14:27.029      card  ANON-0000-0000-0040
240   2024-04-06  2024-04-06 14:49:50.183      card  ANON-0000-0000-0009
241   2024-04-07  2024-04-07 10:12:53.204      card  ANON-0000-0000-0091
242   2024-04-07  2024-04-07 12:44:31.936      card  ANON-0000-0000-0040
243   2024-04-07  2024-04-07 12:46:05.118      card  ANON-0000-0000-0040
244   2024-04-07  2024-04-07 14:16:24.949      card  ANON-0000-0000-0100
245   2024-04-07  2024-04-07 14:17:30.628      card  ANON-0000-0000-0100
246   2024-04-07  2024-04-07 18:01:16.608      card  ANON-0000-0000-0101
247   2024-04-07  2024-04-07 18:02:03.878      card  ANON-0000-0000-0101
250   2024-04-08  2024-04-08 11:01:20.464      card  ANON-0000-0000-0012
252   2024-04-08  2024-04-08 12:54:25.897      cash    payement in cash
253   2024-04-08  2024-04-08 15:43:36.881      cash    payement in cash
254   2024-04-08  2024-04-08 16:41:37.806      card  ANON-0000-0000-0017
256   2024-04-08  2024-04-08 19:22:27.477      card  ANON-0000-0000-0024
257   2024-04-08  2024-04-08 19:23:59.268      card  ANON-0000-0000-0106
258   2024-04-09  2024-04-09 10:22:27.359      cash    payement in cash
259   2024-04-09  2024-04-09 10:24:10.103      cash    payement in cash
260   2024-04-09  2024-04-09 11:42:28.468      card  ANON-0000-0000-0091
262   2024-04-09  2024-04-09 17:25:23.936      card  ANON-0000-0000-0049
263   2024-04-10  2024-04-10 10:21:26.175      cash    payement in cash
264   2024-04-10  2024-04-10 17:55:07.018      cash    payement in cash
266   2024-04-10  2024-04-10 18:24:59.290      card  ANON-0000-0000-0009
268   2024-04-11  2024-04-11 10:41:23.155      card  ANON-0000-0000-0110
269   2024-04-11  2024-04-11 10:42:59.365      card  ANON-0000-0000-0110
270   2024-04-11  2024-04-11 16:35:23.069      card  ANON-0000-0000-0017
271   2024-04-11  2024-04-11 19:16:56.588      card  ANON-0000-0000-0106
272   2024-04-11  2024-04-11 19:18:36.619      card  ANON-0000-0000-0024
273   2024-04-12  2024-04-12 19:03:43.403      card  ANON-0000-0000-0019
274   2024-04-12  2024-04-12 19:38:23.189      card  ANON-0000-0000-0009
275   2024-04-13  2024-04-13 12:29:19.823      card  ANON-0000-0000-0009
276   2024-04-13  2024-04-13 12:43:02.389      card  ANON-0000-0000-0012
277   2024-04-13  2024-04-13 15:06:52.292      cash    payement in cash
278   2024-04-13  2024-04-13 15:07:55.966      cash    payement in cash
279   2024-04-13  2024-04-13 16:18:03.938      card  ANON-0000-0000-0111
280   2024-04-13  2024-04-13 16:19:39.799      card  ANON-0000-0000-0111
282   2024-04-13  2024-04-13 17:53:19.237      card  ANON-0000-0000-0012
283   2024-04-14  2024-04-14 10:55:27.406      cash    payement in cash
285   2024-04-14  2024-04-14 12:27:08.951      cash    payement in cash
286   2024-04-14  2024-04-14 12:29:06.877      cash    payement in cash
287   2024-04-14  2024-04-14 12:31:36.036      cash    payement in cash
289   2024-04-14  2024-04-14 14:23:31.631      card  ANON-0000-0000-0012
290   2024-04-14  2024-04-14 14:24:26.930      card  ANON-0000-0000-0012
291   2024-04-14  2024-04-14 14:25:18.122      card  ANON-0000-0000-0012
292   2024-04-14  2024-04-14 15:46:27.733      card  ANON-0000-0000-0017
293   2024-04-14  2024-04-14 16:59:54.823      card  ANON-0000-0000-0012
294   2024-04-14  2024-04-14 17:00:45.387      card  ANON-0000-0000-0019
295   2024-04-14  2024-04-14 18:38:19.649      card  ANON-0000-0000-0115
296   2024-04-15  2024-04-15 11:45:24.619      card  ANON-0000-0000-0064
297   2024-04-15  2024-04-15 17:01:46.359      card  ANON-0000-0000-0003
298   2024-04-15  2024-04-15 17:02:49.748      card  ANON-0000-0000-0004
299   2024-04-15  2024-04-15 19:33:03.036      card  ANON-0000-0000-0009
300   2024-04-15  2024-04-15 19:41:58.112      cash    payement in cash
301   2024-04-16  2024-04-16 10:43:49.907      cash    payement in cash
304   2024-04-16  2024-04-16 12:52:07.750      card  ANON-0000-0000-0064
305   2024-04-16  2024-04-16 15:03:16.889      card  ANON-0000-0000-0118
306   2024-04-16  2024-04-16 17:42:04.208      card  ANON-0000-0000-0024
307   2024-04-16  2024-04-16 17:43:22.960      card  ANON-0000-0000-0009
308   2024-04-16  2024-04-16 18:09:05.273      card  ANON-0000-0000-0050
309   2024-04-17  2024-04-17 13:32:59.792      card  ANON-0000-0000-0012
311   2024-04-17  2024-04-17 16:13:24.310      cash    payement in cash
312   2024-04-17  2024-04-17 17:01:35.149      card  ANON-0000-0000-0120
313   2024-04-17  2024-04-17 17:02:40.687      card  ANON-0000-0000-0120
315   2024-04-18  2024-04-18 11:19:01.693      card  ANON-0000-0000-0003
316   2024-04-18  2024-04-18 11:20:05.696      card  ANON-0000-0000-0003
317   2024-04-18  2024-04-18 13:49:12.720      card  ANON-0000-0000-0122
318   2024-04-18  2024-04-18 13:50:17.285      card  ANON-0000-0000-0122
319   2024-04-18  2024-04-18 14:34:19.818      card  ANON-0000-0000-0123
320   2024-04-18  2024-04-18 14:35:49.354      card  ANON-0000-0000-0123
321   2024-04-18  2024-04-18 17:44:15.791      card  ANON-0000-0000-0069
322   2024-04-18  2024-04-18 18:21:05.945      card  ANON-0000-0000-0085
323   2024-04-18  2024-04-18 19:39:51.193      card  ANON-0000-0000-0024
324   2024-04-18  2024-04-18 19:40:48.954      card  ANON-0000-0000-0009
325   2024-04-19  2024-04-19 10:10:36.254      card  ANON-0000-0000-0001
326   2024-04-19  2024-04-19 13:11:47.848      card  ANON-0000-0000-0040
327   2024-04-19  2024-04-19 13:13:20.876      card  ANON-0000-0000-0040
328   2024-04-19  2024-04-19 13:58:54.064      card  ANON-0000-0000-0124
329   2024-04-19  2024-04-19 13:59:49.690      card  ANON-0000-0000-0124
330   2024-04-19  2024-04-19 18:23:19.311      card  ANON-0000-0000-0024
331   2024-04-19  2024-04-19 18:25:33.440      card  ANON-0000-0000-0009
332   2024-04-20  2024-04-20 11:24:42.681      cash    payement in cash
333   2024-04-20  2024-04-20 12:08:35.701      card  ANON-0000-0000-0125
334   2024-04-20  2024-04-20 12:09:42.664      card  ANON-0000-0000-0125
335   2024-04-20  2024-04-20 13:08:37.378      card  ANON-0000-0000-0118
336   2024-04-20  2024-04-20 13:09:47.905      card  ANON-0000-0000-0118
337   2024-04-20  2024-04-20 13:10:55.151      card  ANON-0000-0000-0118

In [29]:
# remove the duplicates

In [30]:
##data=data.drop_duplicated()

In [31]:
# basic analysis

In [32]:
data.columns

Index(['date', 'datetime', 'cash_type', 'card', 'money', 'coffee_name'], dtype='object')

In [33]:
data.nunique()

date            381
datetime       3636
cash_type         2
card           1317
money            20
coffee_name       8
dtype: int64

In [34]:
# frequency of coffee by each category

In [35]:
data['cash_type'].value_counts() # value-count is used to count the frequency

cash_type
card    3547
cash      89
Name: count, dtype: int64

In [36]:
# frequency of coffee name

In [37]:
data['coffee_name'].value_counts()

coffee_name
Americano with Milk    824
Latte                  782
Americano              578
Cappuccino             501
Cortado                292
Hot Chocolate          282
Cocoa                  243
Espresso               134
Name: count, dtype: int64

In [38]:
# sorting data

In [39]:
# by deafult sorting is descending

In [42]:
data.sort_values(by="money", ascending =False)

            date                 datetime cash_type                 card  \
60    2024-03-09  2024-03-09 11:49:37.292      cash    payement in cash
117   2024-03-15  2024-03-15 10:02:16.533      cash    payement in cash
126   2024-03-17  2024-03-17 10:10:21.399      cash    payement in cash
225   2024-04-04  2024-04-04 19:42:07.740      cash    payement in cash
264   2024-04-10  2024-04-10 17:55:07.018      cash    payement in cash
152   2024-03-22  2024-03-22 16:15:14.448      cash    payement in cash
232   2024-04-05  2024-04-05 15:30:50.383      cash    payement in cash
233   2024-04-05  2024-04-05 15:54:15.768      cash    payement in cash
76    2024-03-10  2024-03-10 10:06:02.960      cash    payement in cash
235   2024-04-05  2024-04-05 16:17:43.975      cash    payement in cash
311   2024-04-17  2024-04-17 16:13:24.310      cash    payement in cash
164   2024-03-24  2024-03-24 10:03:56.005      cash    payement in cash
89    2024-03-12  2024-03-12 10:15:00.297      cash    payement in cash
82    2024-03-11  2024-03-11 11:24:15.022      cash    payement in cash
190   2024-03-27  2024-03-27 19:31:12.442      cash    payement in cash
210   2024-04-01  2024-04-01 17:01:42.924      cash    payement in cash
283   2024-04-14  2024-04-14 10:55:27.406      cash    payement in cash
105   2024-03-14  2024-03-14 10:02:12.241      cash    payement in cash
46    2024-03-07  2024-03-07 10:08:58.945      cash    payement in cash
200   2024-03-30  2024-03-30 13:49:25.815      cash    payement in cash
258   2024-04-09  2024-04-09 10:22:27.359      cash    payement in cash
49    2024-03-07  2024-03-07 11:25:43.977      cash    payement in cash
198   2024-03-29  2024-03-29 13:22:44.618      cash    payement in cash
278   2024-04-13  2024-04-13 15:07:55.966      cash    payement in cash
144   2024-03-21  2024-03-21 10:18:56.977      cash    payement in cash
81    2024-03-11  2024-03-11 10:18:46.724      cash    payement in cash
12    2024-03-02  2024-03-02 10:30:35.668      cash    payement in cash
18    2024-03-03  2024-03-03 10:10:43.981      cash    payement in cash
216   2024-04-02  2024-04-02 19:59:31.942      cash    payement in cash
277   2024-04-13  2024-04-13 15:06:52.292      cash    payement in cash
137   2024-03-19  2024-03-19 19:26:32.677      cash    payement in cash
139   2024-03-20  2024-03-20 12:21:07.728      cash    payement in cash
342   2024-04-20  2024-04-20 17:07:57.969      cash    payement in cash
514   2024-05-18  2024-05-18 22:05:27.473      cash    payement in cash
628   2024-05-28  2024-05-28 17:21:43.967      cash    payement in cash
634   2024-05-29  2024-05-29 10:48:46.781      cash    payement in cash
580   2024-05-23  2024-05-23 22:55:36.926      cash    payement in cash
657   2024-05-31  2024-05-31 09:23:58.791      cash    payement in cash
549   2024-05-21  2024-05-21 10:05:08.033      cash    payement in cash
548   2024-05-21  2024-05-21 09:46:09.430      cash    payement in cash
677   2024-06-01  2024-06-01 20:54:59.267      cash    payement in cash
492   2024-05-16  2024-05-16 11:44:20.811      cash    payement in cash
348   2024-04-21  2024-04-21 17:09:03.199      cash    payement in cash
491   2024-05-16  2024-05-16 11:42:50.285      cash    payement in cash
447   2024-05-11  2024-05-11 17:02:43.648      cash    payement in cash
442   2024-05-10  2024-05-10 10:09:21.972      cash    payement in cash
409   2024-05-03  2024-05-03 10:11:53.399      cash    payement in cash
403   2024-05-02  2024-05-02 11:29:57.080      cash    payement in cash
353   2024-04-22  2024-04-22 20:02:29.165      cash    payement in cash
351   2024-04-22  2024-04-22 18:40:33.024      cash    payement in cash
195   2024-03-29  2024-03-29 10:56:19.495      card  ANON-0000-0000-0087
196   2024-03-29  2024-03-29 12:34:17.383      card  ANON-0000-0000-0088
197   2024-03-29  2024-03-29 12:41:32.125      card  ANON-0000-0000-0088
0     2024-03-01  2024-03-01 10:15:50.520      card  ANON-0000-0000-0001
199   2024-03-30  2024-03-30 11:59:19.854      card  ANON-0000-0000-0069
201   2024-03-30  2024-03-30 16:12:31.786      card  ANON-0000-0000-0017
202   2024-03-30  2024-03-30 16:36:40.513      card  ANON-0000-0000-0009
204   2024-03-31  2024-03-31 10:40:04.523      card  ANON-0000-0000-0089
212   2024-04-01  2024-04-01 18:45:27.436      card  ANON-0000-0000-0090
194   2024-03-28  2024-03-28 17:32:44.652      card  ANON-0000-0000-0086
213   2024-04-02  2024-04-02 10:01:14.022      card  ANON-0000-0000-0001
169   2024-03-25  2024-03-25 14:29:25.343      card  ANON-0000-0000-0017
187   2024-03-27  2024-03-27 14:22:31.662      card  ANON-0000-0000-0012
165   2024-03-24  2024-03-24 18:45:08.397      card  ANON-0000-0000-0077
141   2024-03-20  2024-03-20 13:16:47.394      card  ANON-0000-0000-0067
142   2024-03-20  2024-03-20 16:42:38.117      card  ANON-0000-0000-0050
143   2024-03-20  2024-03-20 17:50:28.781      card  ANON-0000-0000-0068
146   2024-03-21  2024-03-21 12:26:17.428      card  ANON-0000-0000-0012
149   2024-03-21  2024-03-21 19:20:36.508      card  ANON-0000-0000-0069
156   2024-03-23  2024-03-23 10:43:59.559      card  ANON-0000-0000-0072
158   2024-03-23  2024-03-23 13:10:07.661      card  ANON-0000-0000-0074
159   2024-03-23  2024-03-23 13:11:12.230      card  ANON-0000-0000-0074
161   2024-03-23  2024-03-23 15:47:19.062      card  ANON-0000-0000-0076
166   2024-03-25  2024-03-25 10:31:47.250      card  ANON-0000-0000-0009
186   2024-03-27  2024-03-27 13:35:20.039      card  ANON-0000-0000-0083
168   2024-03-25  2024-03-25 14:27:09.163      card  ANON-0000-0000-0078
221   2024-04-04  2024-04-04 10:44:55.988      card  ANON-0000-0000-0091
171   2024-03-25  2024-03-25 19:34:24.542      card  ANON-0000-0000-0079
172   2024-03-26  2024-03-26 10:35:49.679      card  ANON-0000-0000-0055
173   2024-03-26  2024-03-26 10:36:36.151      card  ANON-0000-0000-0055
174   2024-03-26  2024-03-26 10:42:30.170      card  ANON-0000-0000-0080
180   2024-03-26  2024-03-26 15:48:02.270      card  ANON-0000-0000-0081
181   2024-03-26  2024-03-26 18:33:38.568      card  ANON-0000-0000-0024
182   2024-03-26  2024-03-26 18:34:54.648      card  ANON-0000-0000-0009
219   2024-04-03  2024-04-03 13:12:05.367      card  ANON-0000-0000-0012
251   2024-04-08  2024-04-08 11:04:47.030      card  ANON-0000-0000-0104
222   2024-04-04  2024-04-04 11:26:38.085      card  ANON-0000-0000-0092
223   2024-04-04  2024-04-04 11:27:48.411      card  ANON-0000-0000-0093
284   2024-04-14  2024-04-14 12:24:39.028      card  ANON-0000-0000-0113
292   2024-04-14  2024-04-14 15:46:27.733      card  ANON-0000-0000-0017
294   2024-04-14  2024-04-14 17:00:45.387      card  ANON-0000-0000-0019
295   2024-04-14  2024-04-14 18:38:19.649      card  ANON-0000-0000-0115
303   2024-04-16  2024-04-16 12:40:47.675      card  ANON-0000-0000-0117
307   2024-04-16  2024-04-16 17:43:22.960      card  ANON-0000-0000-0009
308   2024-04-16  2024-04-16 18:09:05.273      card  ANON-0000-0000-0050
312   2024-04-17  2024-04-17 17:01:35.149      card  ANON-0000-0000-0120
319   2024-04-18  2024-04-18 14:34:19.818      card  ANON-0000-0000-0123
320   2024-04-18  2024-04-18 14:35:49.354      card  ANON-0000-0000-0123
321   2024-04-18  2024-04-18 17:44:15.791      card  ANON-0000-0000-0069
322   2024-04-18  2024-04-18 18:21:05.945      card  ANON-0000-0000-0085
323   2024-04-18  2024-04-18 19:39:51.193      card  ANON-0000-0000-0024
324   2024-04-18  2024-04-18 19:40:48.954      card  ANON-0000-0000-0009
325   2024-04-19  2024-04-19 10:10:36.254      card  ANON-0000-0000-0001
327   2024-04-19  2024-04-19 13:13:20.876      card  ANON-0000-0000-0040
328   2024-04-19  2024-04-19 13:58:54.064      card  ANON-0000-0000-0124
329   2024-04-19  2024-04-19 13:59:49.690      card  ANON-0000-0000-0124
330   2024-04-19  2024-04-19 18:23:19.311      card  ANON-0000-0000-0024
337   2024-04-20  2024-04-20 13:10:55.151      card  ANON-0000-0000-0118
338   2024-04-20  2024-04-20 14:44:18.118      card  ANON-0000-0000-0040
282   2024-04-13  2024-04-13 17:53:19.237      card  ANON-0000-0000-0012
281   2024-04-13  2024-04-13 17:51:26.026      card  ANON-0000-0000-0112
280   2024-04-13  2024-04-13 16:19:39.799      card  ANON-0000-0000-0111
254   2024-04-08  2024-04-08 16:41:37.806      card  ANON-0000-0000-0017
230   2024-04-05  2024-04-05 14:23:40.387      card  ANON-0000-0000-0098
238   2024-04-06  2024-04-06 14:13:18.733      card  ANON-0000-0000-0040
240   2024-04-06  2024-04-06 14:49:50.183      card  ANON-0000-0000-0009
241   2024-04-07  2024-04-07 10:12:53.204      card  ANON-0000-0000-0091
242   2024-04-07  2024-04-07 12:44:31.936      card  ANON-0000-0000-0040
243   2024-04-07  2024-04-07 12:46:05.118      card  ANON-0000-0000-0040
246   2024-04-07  2024-04-07 18:01:16.608      card  ANON-0000-0000-0101
249   2024-04-08  2024-04-08 10:59:27.558      card  ANON-0000-0000-0103
134   2024-03-19  2024-03-19 14:03:19.765      card  ANON-0000-0000-0065
257   2024-04-08  2024-04-08 19:23:59.268      card  ANON-0000-0000-0106
279   2024-04-13  2024-04-13 16:18:03.938      card  ANON-0000-0000-0111
260   2024-04-09  2024-04-09 11:42:28.468      card  ANON-0000-0000-0091
261   2024-04-09  2024-04-09 15:11:48.720      card  ANON-0000-0000-0107
262   2024-04-09  2024-04-09 17:25:23.936      card  ANON-0000-0000-0049
266   2024-04-10  2024-04-10 18:24:59.290      card  ANON-0000-0000-0009
267   2024-04-10  2024-04-10 20:04:05.386      card  ANON-0000-0000-0109
270   2024-04-11  2024-04-11 16:35:23.069      card  ANON-0000-0000-0017
271   2024-04-11  2024-04-11 19:16:56.588      card  ANON-0000-0000-0106
273   2024-04-12  2024-04-12 19:03:43.403      card  ANON-0000-0000-0019
275   2024-04-13  2024-04-13 12:29:19.823      card  ANON-0000-0000-0009
135   2024-03-19  2024-03-19 15:04:36.309      card  ANON-0000-0000-0049
313   2024-04-17  2024-04-17 17:02:40.687      card  ANON-0000-0000-0120
133   2024-03-19  2024-03-19 14:02:21.536      card  ANON-0000-0000-0065
112   2024-03-14  2024-03-14 15:20:38.367      card  ANON-0000-0000-0058
92    2024-03-12  2024-03-12 11:20:45.632      card  ANON-0000-0000-0049
38    2024-03-05  2024-03-05 17:38:09.354      card  ANON-0000-0000-0009
37    2024-03-05  2024-03-05 17:37:13.659      card  ANON-0000-0000-0027
96    2024-03-13  2024-03-13 11:06:43.038      card  ANON-0000-0000-0048
63    2024-03-09  2024-03-09 12:09:47.714      card  ANON-0000-0000-0012
35    2024-03-05  2024-03-05 17:35:25.021      card  ANON-0000-0000-0025
1     2024-03-01  2024-03-01 12:19:22.539      card  ANON-0000-0000-0002
34    2024-03-05  2024-03-05 17:34:06.043      card  ANON-0000-0000-0024
33    2024-03-05  2024-03-05 14:34:55.963      card  ANON-0000-0000-0023
32    2024-03-05  2024-03-05 09:59:52.651      card  ANON-0000-0000-0001
29    2024-03-04  2024-03-04 10:54:50.958      card  ANON-0000-0000-0021
106   2024-03-14  2024-03-14 10:28:33.017      card  ANON-0000-0000-0055
107   2024-03-14  2024-03-14 10:29:34.283      card  ANON-0000-0000-0055
28    2024-03-04  2024-03-04 10:03:51.994      card  ANON-0000-0000-0001
27    2024-03-03  2024-03-03 18:08:04.959      card  ANON-0000-0000-0020
6     2024-03-01  2024-03-01 16:19:02.756      card  ANON-0000-0000-0006
87    2024-03-11  2024-03-11 16:25:45.664      card  ANON-0000-0000-0047
40    2024-03-05  2024-03-05 18:01:31.242      card  ANON-0000-0000-0028
72    2024-03-09  2024-03-09 19:17:57.572      card  ANON-0000-0000-0009
59    2024-03-08  2024-03-08 18:59:24.941      card  ANON-0000-0000-0037
66    2024-03-09  2024-03-09 13:09:22.229      card  ANON-0000-0000-0041
58    2024-03-08  2024-03-08 18:57:51.451      card  ANON-0000-0000-0036
69    2024-03-09  2024-03-09 13:54:36.828      card  ANON-0000-0000-0043
53    2024-03-08  2024-03-08 12:22:28.653      card  ANON-0000-0000-0034
71    2024-03-09  2024-03-09 14:26:52.873      card  ANON-0000-0000-0044
73    2024-03-09  2024-03-09 19:19:10.084      card  ANON-0000-0000-0009
85    2024-03-11  2024-03-11 11:32:58.781      card  ANON-0000-0000-0035
48    2024-03-07  2024-03-07 11:03:58.976      card  ANON-0000-0000-0031
47    2024-03-07  2024-03-07 10:18:40.543      card  ANON-0000-0000-0030
45    2024-03-06  2024-03-06 14:53:18.344      card  ANON-0000-0000-0029
44    2024-03-06  2024-03-06 14:52:01.761      card  ANON-0000-0000-0029
79    2024-03-10  2024-03-10 19:34:00.478      card  ANON-0000-0000-0046
8     2024-03-01  2024-03-01 19:22:01.762      card  ANON-0000-0000-0008
4     2024-03-01  2024-03-01 13:48:14.626      card  ANON-0000-0000-0004
36    2024-03-05  2024-03-05 17:36:28.571      card  ANON-0000-0000-0026
19    2024-03-03  2024-03-03 10:27:18.561      card  ANON-0000-0000-0015
118   2024-03-15  2024-03-15 10:53:02.180      card  ANON-0000-0000-0060
2     2024-03-01  2024-03-01 12:20:18.089      card  ANON-0000-0000-0002
115   2024-03-14  2024-03-14 18:58:55.854      card  ANON-0000-0000-0019
23    2024-03-03  2024-03-03 17:06:40.271      card  ANON-0000-0000-0018
22    2024-03-03  2024-03-03 13:09:36.321      card  ANON-0000-0000-0017
455   2024-05-12  2024-05-12 13:24:03.465      card  ANON-0000-0000-0160
378   2024-04-26  2024-04-26 19:32:07.112      card  ANON-0000-0000-0009
379   2024-04-26  2024-04-26 19:33:30.220      card  ANON-0000-0000-0009
380   2024-04-27  2024-04-27 15:27:00.680      card  ANON-0000-0000-0009
382   2024-04-28  2024-04-28 12:30:09.749      card  ANON-0000-0000-0140
454   2024-05-12  2024-05-12 10:20:42.512      card  ANON-0000-0000-0001
754   2024-06-10  2024-06-10 19:38:19.678      card  ANON-0000-0000-0283
453   2024-05-11  2024-05-11 19:38:16.096      card  ANON-0000-0000-0159
405   2024-05-02  2024-05-02 18:36:22.138      card  ANON-0000-0000-0144
452   2024-05-11  2024-05-11 18:35:40.257      card  ANON-0000-0000-0115
718   2024-06-06  2024-06-06 10:36:09.667      card  ANON-0000-0000-0001
721   2024-06-06  2024-06-06 15:24:06.221      card  ANON-0000-0000-0266
450   2024-05-11  2024-05-11 17:23:57.301      card  ANON-0000-0000-0040
449   2024-05-11  2024-05-11 17:21:56.117      card  ANON-0000-0000-0026
722   2024-06-06  2024-06-06 21:14:05.102      card  ANON-0000-0000-0267
446   2024-05-11  2024-05-11 11:39:52.878      card  ANON-0000-0000-0069
753   2024-06-10  2024-06-10 19:37:23.602      card  ANON-0000-0000-0283
723   2024-06-06  2024-06-06 21:15:42.227      card  ANON-0000-0000-0267
457   2024-05-12  2024-05-12 15:16:19.815      card  ANON-0000-0000-0077
757   2024-06-11  2024-06-11 18:49:36.428      card  ANON-0000-0000-0285
714   2024-06-05  2024-06-05 20:10:47.623      card  ANON-0000-0000-0220
756   2024-06-11  2024-06-11 18:48:25.292      card  ANON-0000-0000-0285
477   2024-05-15  2024-05-15 08:40:05.661      card  ANON-0000-0000-0168
476   2024-05-14  2024-05-14 22:51:25.227      card  ANON-0000-0000-0167
368   2024-04-25  2024-04-25 15:18:26.971      card  ANON-0000-0000-0009
475   2024-05-14  2024-05-14 16:59:10.194      card  ANON-0000-0000-0166
371   2024-04-26  2024-04-26 10:12:50.618      card  ANON-0000-0000-0001
707   2024-06-05  2024-06-05 08:21:48.964      card  ANON-0000-0000-0261
708   2024-06-05  2024-06-05 08:23:06.723      card  ANON-0000-0000-0261
471   2024-05-14  2024-05-14 14:04:54.580      card  ANON-0000-0000-0025
470   2024-05-14  2024-05-14 11:34:12.851      card  ANON-0000-0000-0165
469   2024-05-14  2024-05-14 11:32:29.372      card  ANON-0000-0000-0165
468   2024-05-14  2024-05-14 10:19:23.174      card  ANON-0000-0000-0012
372   2024-04-26  2024-04-26 12:01:30.580      card  ANON-0000-0000-0136
710   2024-06-05  2024-06-05 10:28:50.620      card  ANON-0000-0000-0001
713   2024-06-05  2024-06-05 19:59:53.527      card  ANON-0000-0000-0264
373   2024-04-26  2024-04-26 13:31:28.297      card  ANON-0000-0000-0137
758   2024-06-11  2024-06-11 21:17:03.344      card  ANON-0000-0000-0286
443   2024-05-10  2024-05-10 15:46:21.511      card  ANON-0000-0000-0158
444   2024-05-10  2024-05-10 15:47:32.508      card  ANON-0000-0000-0158
752   2024-06-10  2024-06-10 19:05:22.770      card  ANON-0000-0000-0282
385   2024-04-28  2024-04-28 18:29:02.374      card  ANON-0000-0000-0019
394   2024-04-30  2024-04-30 10:16:41.493      card  ANON-0000-0000-0142
746   2024-06-09  2024-06-09 16:17:28.189      card  ANON-0000-0000-0278
421   2024-05-06  2024-05-06 19:19:49.548      card  ANON-0000-0000-0151
420   2024-05-06  2024-05-06 19:18:12.989      card  ANON-0000-0000-0151
734   2024-06-08  2024-06-08 20:24:54.320      card  ANON-0000-0000-0134
735   2024-06-08  2024-06-08 20:25:56.316      card  ANON-0000-0000-0134
736   2024-06-09  2024-06-09 08:15:52.760      card  ANON-0000-0000-0097
744   2024-06-09  2024-06-09 12:14:10.783      card  ANON-0000-0000-0276
737   2024-06-09  2024-06-09 10:30:04.461      card  ANON-0000-0000-0272
738   2024-06-09  2024-06-09 10:52:05.797      card  ANON-0000-0000-0273
399   2024-04-30  2024-04-30 19:19:18.139      card  ANON-0000-0000-0142
743   2024-06-09  2024-06-09 12:13:08.067      card  ANON-0000-0000-0276
413   2024-05-06  2024-05-06 10:06:51.625      card  ANON-0000-0000-0149
401   2024-04-30  2024-04-30 19:31:20.952      card  ANON-0000-0000-0142
411   2024-05-03  2024-05-03 17:03:24.905      card  ANON-0000-0000-0147
410   2024-05-03  2024-05-03 14:30:00.923      card  ANON-0000-0000-0146
741   2024-06-09  2024-06-09 11:52:49.616      card  ANON-0000-0000-0275
408   2024-05-02  2024-05-02 19:19:56.359      card  ANON-0000-0000-0145
422   2024-05-07  2024-05-07 10:44:55.582      card  ANON-0000-0000-0148
393   2024-04-29  2024-04-29 19:13:37.878      card  ANON-0000-0000-0134
407   2024-05-02  2024-05-02 19:18:33.084      card  ANON-0000-0000-0145
425   2024-05-07  2024-05-07 16:42:07.900      card  ANON-0000-0000-0148
724   2024-06-06  2024-06-06 21:18:26.713      card  ANON-0000-0000-0206
726   2024-06-06  2024-06-06 21:21:04.440      card  ANON-0000-0000-0267
727   2024-06-07  2024-06-07 08:18:04.296      card  ANON-0000-0000-0268
437   2024-05-09  2024-05-09 13:07:16.409      card  ANON-0000-0000-0156
436   2024-05-09  2024-05-09 13:06:11.261      card  ANON-0000-0000-0156
435   2024-05-09  2024-05-09 13:04:57.647      card  ANON-0000-0000-0156
433   2024-05-09  2024-05-09 12:54:21.812      card  ANON-0000-0000-0155
432   2024-05-08  2024-05-08 10:07:28.863      card  ANON-0000-0000-0001
751   2024-06-10  2024-06-10 19:04:28.106      card  ANON-0000-0000-0282
431   2024-05-07  2024-05-07 19:13:12.195      card  ANON-0000-0000-0154
430   2024-05-07  2024-05-07 19:12:12.524      card  ANON-0000-0000-0154
750   2024-06-10  2024-06-10 12:56:48.268      card  ANON-0000-0000-0097
428   2024-05-07  2024-05-07 17:38:48.195      card  ANON-0000-0000-0153
749   2024-06-10  2024-06-10 12:47:49.861      card  ANON-0000-0000-0281
391   2024-04-29  2024-04-29 18:37:48.406      card  ANON-0000-0000-0140
427   2024-05-07  2024-05-07 17:37:46.412      card  ANON-0000-0000-0153
392   2024-04-29  2024-04-29 19:12:33.194      card  ANON-0000-0000-0134
701   2024-06-04  2024-06-04 20:50:33.896      card  ANON-0000-0000-0257
496   2024-05-16  2024-05-16 18:12:56.934      card  ANON-0000-0000-0175
700   2024-06-04  2024-06-04 20:13:01.204      card  ANON-0000-0000-0256
699   2024-06-04  2024-06-04 17:47:28.847      card  ANON-0000-0000-0192
644   2024-05-30  2024-05-30 08:29:06.277      card  ANON-0000-0000-0241
645   2024-05-30  2024-05-30 08:30:21.586      card  ANON-0000-0000-0241
589   2024-05-25  2024-05-25 12:13:53.388      card  ANON-0000-0000-0211
647   2024-05-30  2024-05-30 09:47:59.092      card  ANON-0000-0000-0001
584   2024-05-24  2024-05-24 16:07:19.816      card  ANON-0000-0000-0081
651   2024-05-30  2024-05-30 19:53:11.189      card  ANON-0000-0000-0206
652   2024-05-30  2024-05-30 20:31:05.430      card  ANON-0000-0000-0244
653   2024-05-30  2024-05-30 20:46:13.835      card  ANON-0000-0000-0009
578   2024-05-23  2024-05-23 20:16:24.205      card  ANON-0000-0000-0207
577   2024-05-23  2024-05-23 20:15:01.429      card  ANON-0000-0000-0207