# SALES ANALYSIS

# IMPORTING DATA

In [1]:
# mehtod 1 using link

In [2]:
import numpy as np
import pandas as pd

In [11]:
#data=pd.read_csv("C:\\Users\\ASUS\\Desktop\\Sales.csv")

In [12]:
#data

In [8]:
#method 2

In [9]:
data=pd.read_csv("sales.csv")

In [13]:
data

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3109,POCO,M4 Pro 5G,Cool Blue,6 GB,128 GB,Yes,4.4,16999,19999,POCO M4 Pro 5G,3000,15.000750
3110,Nokia,225,Black,NaN,Expandable Upto 32 GB,Yes,3.6,3499,3499,Nokia 225,0,0.000000
3111,Apple,iPhone SE,White,2 GB,128 GB,Yes,4.5,44900,44900,Apple iPhone SE,0,0.000000
3112,Apple,iPhone 13 Pro,Gold,6 GB,128 GB,Yes,NaN,119900,119900,Apple iPhone 13 Pro,0,0.000000
3113,GIONEE,F9,Blue,3 GB,32 GB,Yes,4.2,7900,7900,GIONEE F9,0,0.000000

In [14]:
# basic data exploration

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3114 entries, 0 to 3113
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brands               3114 non-null   object
 1   Models               3114 non-null   object
 2   Colors               3114 non-null   object
 3   Memory               3071 non-null   object
 4   Storage              3075 non-null   object
 5   Camera               3114 non-null   object
 6   Rating               2970 non-null   float64
 7   Selling Price        3114 non-null   int64
 8   Original Price       3114 non-null   int64
 9   Mobile               3114 non-null   object
 10  Discount             3114 non-null   int64
 11  discount percentage  3114 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 292.1+ KB

In [16]:
data.describe()

,Rating,Selling Price,Original Price,Discount,discount percentage
count,2970.000000,3114.000000,3114.000000,3114.000000,3114.000000
mean,4.243098,26436.625562,28333.473025,1896.847463,6.086788
std,0.271991,30066.892622,31525.599889,5337.126176,11.106776
min,2.300000,1000.000000,1000.000000,-8000.000000,-160.320641
25%,4.100000,9990.000000,10030.250000,0.000000,0.000000
50%,4.300000,15000.000000,16889.500000,0.000000,0.000000
75%,4.400000,28999.000000,31500.000000,2000.000000,9.836388
max,5.000000,179900.000000,189999.000000,75000.000000,70.610305

In [17]:
data.head()

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000

In [18]:
data.tail()

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
3109,POCO,M4 Pro 5G,Cool Blue,6 GB,128 GB,Yes,4.4,16999,19999,POCO M4 Pro 5G,3000,15.00075
3110,Nokia,225,Black,NaN,Expandable Upto 32 GB,Yes,3.6,3499,3499,Nokia 225,0,0.00000
3111,Apple,iPhone SE,White,2 GB,128 GB,Yes,4.5,44900,44900,Apple iPhone SE,0,0.00000
3112,Apple,iPhone 13 Pro,Gold,6 GB,128 GB,Yes,NaN,119900,119900,Apple iPhone 13 Pro,0,0.00000
3113,GIONEE,F9,Blue,3 GB,32 GB,Yes,4.2,7900,7900,GIONEE F9,0,0.00000

In [19]:
data.shape

(3114, 12)

In [20]:
data.columns

Index(['Brands', 'Models', 'Colors', 'Memory', 'Storage', 'Camera', 'Rating',
       'Selling Price', 'Original Price', 'Mobile', 'Discount',
       'discount percentage'],
      dtype='object')

In [22]:
data.dtypes

Brands                  object
Models                  object
Colors                  object
Memory                  object
Storage                 object
Camera                  object
Rating                 float64
Selling Price            int64
Original Price           int64
Mobile                  object
Discount                 int64
discount percentage    float64
dtype: object

In [23]:
# misisng value analysis

In [24]:
data.isnull().sum()

Brands                   0
Models                   0
Colors                   0
Memory                  43
Storage                 39
Camera                   0
Rating                 144
Selling Price            0
Original Price           0
Mobile                   0
Discount                 0
discount percentage      0
dtype: int64

In [26]:
missing_percentage=(data.isnull().sum()/len(data))*100
print(missing_percentage)

Brands                 0.000000
Models                 0.000000
Colors                 0.000000
Memory                 1.380861
Storage                1.252408
Camera                 0.000000
Rating                 4.624277
Selling Price          0.000000
Original Price         0.000000
Mobile                 0.000000
Discount               0.000000
discount percentage    0.000000
dtype: float64

In [27]:
# since the missing the percentage is not huge so we can replace it by mean

In [29]:
#converting the column to numeric

In [30]:
# memory

In [32]:
data["Memory"]=data["Memory"].str.replace("GB", "",regex=False).str.strip()
data["Memory"]=pd.to_numeric(data["Memory"],errors="coerce")

In [33]:
data

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128 GB,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2.0,16 GB,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2.0,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4.0,64 GB,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4.0,64 GB,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3109,POCO,M4 Pro 5G,Cool Blue,6.0,128 GB,Yes,4.4,16999,19999,POCO M4 Pro 5G,3000,15.000750
3110,Nokia,225,Black,NaN,Expandable Upto 32 GB,Yes,3.6,3499,3499,Nokia 225,0,0.000000
3111,Apple,iPhone SE,White,2.0,128 GB,Yes,4.5,44900,44900,Apple iPhone SE,0,0.000000
3112,Apple,iPhone 13 Pro,Gold,6.0,128 GB,Yes,NaN,119900,119900,Apple iPhone 13 Pro,0,0.000000
3113,GIONEE,F9,Blue,3.0,32 GB,Yes,4.2,7900,7900,GIONEE F9,0,0.000000

In [34]:
data["Storage"]=data["Storage"].str.replace("GB", "",regex=False).str.strip()
data["Storage"]=pd.to_numeric(data["Storage"],errors="coerce")

In [35]:
data

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.0,128.0,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2.0,16.0,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2.0,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4.0,64.0,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4.0,64.0,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3109,POCO,M4 Pro 5G,Cool Blue,6.0,128.0,Yes,4.4,16999,19999,POCO M4 Pro 5G,3000,15.000750
3110,Nokia,225,Black,NaN,NaN,Yes,3.6,3499,3499,Nokia 225,0,0.000000
3111,Apple,iPhone SE,White,2.0,128.0,Yes,4.5,44900,44900,Apple iPhone SE,0,0.000000
3112,Apple,iPhone 13 Pro,Gold,6.0,128.0,Yes,NaN,119900,119900,Apple iPhone 13 Pro,0,0.000000
3113,GIONEE,F9,Blue,3.0,32.0,Yes,4.2,7900,7900,GIONEE F9,0,0.000000

In [38]:
data["Memory"]=data["Memory"].fillna(data["Memory"].mean())

In [40]:
data

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.000000,128.0,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2.000000,16.0,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2.000000,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4.000000,64.0,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4.000000,64.0,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3109,POCO,M4 Pro 5G,Cool Blue,6.000000,128.0,Yes,4.4,16999,19999,POCO M4 Pro 5G,3000,15.000750
3110,Nokia,225,Black,4.353801,NaN,Yes,3.6,3499,3499,Nokia 225,0,0.000000
3111,Apple,iPhone SE,White,2.000000,128.0,Yes,4.5,44900,44900,Apple iPhone SE,0,0.000000
3112,Apple,iPhone 13 Pro,Gold,6.000000,128.0,Yes,NaN,119900,119900,Apple iPhone 13 Pro,0,0.000000
3113,GIONEE,F9,Blue,3.000000,32.0,Yes,4.2,7900,7900,GIONEE F9,0,0.000000

In [41]:
data["Storage"]=data["Storage"].fillna(data["Storage"].mean())

In [42]:
data["Rating"]=data["Rating"].fillna(data["Rating"].mean())

In [43]:
data

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8.000000,128.000000,Yes,4.300000,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2.000000,16.000000,Yes,3.800000,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2.000000,91.878944,Yes,4.400000,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4.000000,64.000000,Yes,4.200000,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4.000000,64.000000,Yes,4.600000,49900,49900,Apple iPhone 11,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3109,POCO,M4 Pro 5G,Cool Blue,6.000000,128.000000,Yes,4.400000,16999,19999,POCO M4 Pro 5G,3000,15.000750
3110,Nokia,225,Black,4.353801,91.878944,Yes,3.600000,3499,3499,Nokia 225,0,0.000000
3111,Apple,iPhone SE,White,2.000000,128.000000,Yes,4.500000,44900,44900,Apple iPhone SE,0,0.000000
3112,Apple,iPhone 13 Pro,Gold,6.000000,128.000000,Yes,4.243098,119900,119900,Apple iPhone 13 Pro,0,0.000000
3113,GIONEE,F9,Blue,3.000000,32.000000,Yes,4.200000,7900,7900,GIONEE F9,0,0.000000

In [44]:
data.duplicated().sum()

np.int64(111)

In [45]:
data[data.duplicated()]

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
16,Apple,iPhone 13 Mini,Pink,6.000000,512.000000,Yes,4.243098,99900,99900,Apple iPhone 13 Mini,0,0.0
178,Apple,iPhone 11,White,4.000000,256.000000,Yes,4.600000,64900,64900,Apple iPhone 11,0,0.0
338,Nokia,C01 Plus,Blue,2.000000,16.000000,Yes,4.243098,6499,6499,Nokia C01 Plus,0,0.0
525,SAMSUNG,Guru Music 2,Black,4.353801,91.878944,Yes,4.300000,1625,1625,SAMSUNG Guru Music 2,0,0.0
765,SAMSUNG,Guru Music 2,Black,4.353801,91.878944,Yes,4.300000,1625,1625,SAMSUNG Guru Music 2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3041,Apple,iPhone SE,Red,2.000000,128.000000,Yes,4.500000,44900,44900,Apple iPhone SE,0,0.0
3052,Apple,iPhone 11,Purple,4.000000,128.000000,Yes,4.600000,54900,54900,Apple iPhone 11,0,0.0
3071,Apple,iPhone 7,Red,2.000000,256.000000,Yes,4.700000,74400,74400,Apple iPhone 7,0,0.0
3110,Nokia,225,Black,4.353801,91.878944,Yes,3.600000,3499,3499,Nokia 225,0,0.0
3111,Apple,iPhone SE,White,2.000000,128.000000,Yes,4.500000,44900,44900,Apple iPhone SE,0,0.0

In [46]:
# how to get cleaned data file in csv

In [47]:
data.to_csv("sales_cleaned.csv",index=False)

# Brand analysis

In [48]:
# number of mobiles by each brand

In [50]:
data["Brands"].value_counts()

Brands
SAMSUNG         719
Apple           387
realme          327
OPPO            260
Nokia           213
Xiaomi          198
Infinix         151
GIONEE          129
vivo            124
Lenovo          121
ASUS            118
Motorola        105
LG               99
POCO             74
HTC              55
Google Pixel     29
IQOO              5
Name: count, dtype: int64

In [51]:
# top 10 brands

In [52]:
data["Brands"].value_counts().head(10)

Brands
SAMSUNG    719
Apple      387
realme     327
OPPO       260
Nokia      213
Xiaomi     198
Infinix    151
GIONEE     129
vivo       124
Lenovo     121
Name: count, dtype: int64

In [53]:
#bottom 10 brands

In [54]:
data["Brands"].value_counts().tail(10)

Brands
GIONEE          129
vivo            124
Lenovo          121
ASUS            118
Motorola        105
LG               99
POCO             74
HTC              55
Google Pixel     29
IQOO              5
Name: count, dtype: int64

# selling price analysis

In [55]:
data["Selling Price"].mean()

np.float64(26436.625561978162)

In [56]:
# most expensive mobile

In [59]:
data.loc[data["Selling Price"].idxmax()]

Brands                                    Apple
Models                       iPhone 13 Pro Max
Colors                                     Gold
Memory                                      6.0
Storage                               91.878944
Camera                                      Yes
Rating                                 4.243098
Selling Price                            179900
Original Price                           179900
Mobile                 Apple iPhone 13 Pro Max
Discount                                      0
discount percentage                         0.0
Name: 323, dtype: object

In [60]:
#cheapest mobile 
data.loc[data["Selling Price"].idxmin()]

Brands                     Nokia
Models                       105
Colors                     Black
Memory                  4.353801
Storage                91.878944
Camera                       Yes
Rating                       4.3
Selling Price               1000
Original Price              1000
Mobile                 Nokia 105
Discount                       0
discount percentage          0.0
Name: 1501, dtype: object

In [61]:
data.loc[data["Rating"].idxmax()]

Brands                       vivo
Models                      X50
Colors                 Frost Blue
Memory                        8.0
Storage                     256.0
Camera                        Yes
Rating                        5.0
Selling Price               44990
Original Price              44990
Mobile                 vivo X50
Discount                        0
discount percentage           0.0
Name: 247, dtype: object

In [62]:
#highest discount

In [63]:
data.loc[data["Discount"].idxmax()]

Brands                       Motorola
Models                          Razr
Colors                           Gold
Memory                            6.0
Storage                         128.0
Camera                            Yes
Rating                            3.8
Selling Price                   74999
Original Price                 149999
Mobile                 Motorola Razr
Discount                        75000
discount percentage         50.000333
Name: 589, dtype: object

In [64]:
#average selling price by brand

In [65]:
data.groupby("Brands")["Selling Price"].mean().sort_values(ascending=False)

Brands
Apple           81985.560724
Google Pixel    61391.862069
IQOO            37190.000000
HTC             28314.381818
SAMSUNG         24296.248957
vivo            23866.241935
ASUS            20326.915254
LG              19323.181818
OPPO            18560.488462
Xiaomi          16941.909091
POCO            16870.621622
realme          16396.535168
Motorola        16357.466667
Infinix         11092.178808
Lenovo          10083.842975
Nokia            9428.657277
GIONEE           7135.093023
Name: Selling Price, dtype: float64

In [66]:
#average rating by brand

In [69]:
data.groupby("Brands")["Rating"].mean().sort_values(ascending=False)

Brands
Apple           4.525282
Google Pixel    4.506897
IQOO            4.400000
POCO            4.385718
realme          4.383412
vivo            4.373748
Xiaomi          4.302821
OPPO            4.296492
Infinix         4.276821
SAMSUNG         4.208726
Motorola        4.144630
ASUS            4.092387
Nokia           4.029002
LG              3.984274
Lenovo          3.977216
HTC             3.969091
GIONEE          3.857257
Name: Rating, dtype: float64

In [68]:
#average memeory by brand

In [70]:
data.groupby("Brands")["Memory"].mean().sort_values(ascending=False)

Brands
IQOO            8.800000
vivo            5.847269
POCO            5.770270
realme          5.431193
OPPO            5.057692
Xiaomi          4.865423
SAMSUNG         4.714491
ASUS            4.296610
Infinix         3.986755
Motorola        3.959120
Google Pixel    3.724138
Nokia           3.705941
Apple           3.536433
LG              3.362780
GIONEE          2.660819
Lenovo          2.620342
HTC             2.431047
Name: Memory, dtype: float64

In [71]:
# average storage by brand

In [72]:
data.groupby("Brands")["Storage"].mean().sort_values(ascending=False)

Brands
IQOO            204.800000
Apple           187.839331
vivo            109.935484
POCO            108.540541
realme          100.966377
OPPO             95.753846
Xiaomi           87.469697
SAMSUNG          85.319354
Google Pixel     81.655172
ASUS             75.932203
Motorola         64.380952
Infinix          62.622517
Nokia            59.317740
LG               48.969697
HTC              32.145455
GIONEE           30.783190
Lenovo           27.999000
Name: Storage, dtype: float64

In [73]:
# total discount by brand

In [74]:
data.groupby("Brands")["Discount"].sum().sort_values(ascending=False)

Brands
SAMSUNG         1823227
Apple           1134611
OPPO             533202
realme           471403
Motorola         454009
LG               301415
vivo             210386
POCO             193500
Xiaomi           180446
Nokia            158841
ASUS             148500
Infinix          139812
GIONEE            88174
Lenovo            32267
IQOO              19000
Google Pixel      17990
HTC                   0
Name: Discount, dtype: int64