In [1]:
import numpy as np

In [2]:
import numpy

In [3]:
# numpy library -- use in working with numbers 
# stastical analysiss - mean , median , mode, arthemtic function , number , arrays 
# numpy

In [63]:
##print (dir(np))

In [64]:
##help (np)

In [6]:
# what is the difference numpy and pandas ?

# numpy :
numpy : arrays (ndrray )
homogenous (same type)
numerical computation 
very fast (low-level)
math , matrices , ml core

# Pandas :
series , dataframe 
hetrogenous (different data types)
data analysis and manipualtion 
data cleaning and analytics

ndarray in numpy : 
n dimenssioanl array it is core of data structure 
array - it is linear data structure (homogenous data type )
a=[1,2,3,45]

series : series in pandas is a 1D array like a single colum

In [8]:
# ex of series in pandas 
import pandas as pd 
s=pd.Series ([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64

In [9]:
# dataframe : it is a 2dimenssional table like excel sheet

In [11]:
import pandas as pd 
data ={
    "name":["mudit","anurag","anshu"],
    "age":[20,22,23],
    "Marks":[90,90,90]
}
df=pd.DataFrame(data)
print(df)

     name  age  Marks
0   mudit   20     90
1  anurag   22     90
2   anshu   23     90

In [12]:
# python dictionary strture ,purpose

In [16]:
# pandas , numpy : libraries and packages and inside each library there is a function

In [17]:
print (dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [18]:
# import pandas as pd

In [20]:
from pandas import tseries # only function from particular moddule

In [22]:
# module package not installed

In [25]:
##pip install pandas ## pip command is used to import any module

In [26]:
## import csv file using pandas

In [27]:
import pandas as pd

In [28]:
data =pd.read_csv("ecommerce_10000.csv")

In [29]:
data

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

pd.read_Excel("ecommerce_1000.xlsx") if the file is excel

In [32]:
data=pd.read_csv("C:\Users\Mittansh\Downloads\ecommerce_10000.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2320305639.py, line 1)

In [33]:
##SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

##Click to add a cell.

In [34]:
data=pd.read_csv("C:\\Users\\Mittansh\\Downloads\\ecommerce_10000.csv")

In [35]:
data

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

In [37]:
np.shape(data) ## shape function is used in numpy to see the structure of data

(10000, 12)

In [40]:
data.head() # head is used for seei g first five rows

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19

In [41]:
data.tail() # tail is to see last five rows

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

In [42]:
data.head(50)

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
5,ORD100005,T-shirt Cotton,Fashion,Generic,Souq,Riyadh,19869.86,5,99349.30,3.91,2154,2024-09-28
6,ORD100006,T-shirt Cotton,Fashion,Generic,Souq,Casablanca,17796.11,2,35592.22,4.18,4309,2024-07-02
7,ORD100007,Smartwatch FitPro,Wearables,FitPro,Souq,Casablanca,13081.14,3,39243.42,2.98,3504,2024-01-30
8,ORD100008,T-shirt Cotton,Fashion,Generic,Amazon,Dubai,510.30,5,2551.50,1.17,178,2024-09-21
9,ORD100009,Xiaomi Redmi Note 12,Electronics,Xiaomi,Jumia,Riyadh,6326.57,3,18979.71,2.05,4589,2024-09-26
10,ORD100010,Samsung Galaxy A14,Electronics,Samsung,Jumia,Riyadh,10283.51,1,10283.51,3.05,4702,2024-02-20
11,ORD100011,Dell Inspiron 3501,Computers,Dell,Jumia,Casablanca,451.79,2,903.58,4.28,618,2024-05-18
12,ORD100012,HP Pavilion Laptop,Computers,HP,Souq,Dubai,5904.49,3,17713.47,2.60,1215,2024-08-09
13,ORD100013,HP Pavilion Laptop,Computers,HP,Jumia,Dubai,19853.19,4,79412.76,3.46,2143,2024-04-06
14,ORD100014,HP Pavilion Laptop,Computers,HP,Jumia,Alexandria,17920.82,4,71683.28,4.84,2166,2024-07-11
15,ORD100015,Xiaomi Redmi Note 12,Electronics,Xiaomi,Amazon,Cairo,15802.27,5,79011.35,1.75,1853,2024-02-02
16,ORD100016,Samsung Galaxy A14,Electronics,Samsung,Souq,Alexandria,3529.77,5,17648.85,2.06,717,2024-05-09
17,ORD100017,Dell Inspiron 3501,Computers,Dell,Amazon,Cairo,13247.77,3,39743.31,3.86,4403,2024-12-17
18,ORD100018,iPhone 13,Electronics,Apple,Amazon,Giza,13936.49,2,27872.98,1.42,153,2024-01-24
19,ORD100019,T-shirt Cotton,Fashion,Generic,Souq,Cairo,5953.25,3,17859.75,1.99,3079,2024-03-12
20,ORD100020,Adidas Running Shoes,Fashion,Adidas,Amazon,Dubai,9716.95,4,38867.80,1.76,60,2024-06-28
21,ORD100021,Samsung Galaxy A14,Electronics,Samsung,Jumia,Casablanca,12134.55,4,48538.20,4.61,2413,2024-01-28
22,ORD100022,iPhone 13,Electronics,Apple,Jumia,Alexandria,3597.29,1,3597.29,4.63,2559,2024-04-07
23,ORD100023,Dell Inspiron 3501,Computers,Dell,Jumia,Casablanca,17087.44,3,51262.32,4.75,2187,2024-01-07
24,ORD100024,Samsung Galaxy A14,Electronics,Samsung,Souq,Dubai,7396.38,2,14792.76,4.34,1123,2024-02-08
25,ORD100025,Xiaomi Redmi Note 12,Electronics,Xiaomi,Souq,Casablanca,15915.39,5,79576.95,1.73,534,2024-01-02
26,ORD100026,iPhone 13,Electronics,Apple,Souq,Dubai,14633.56,4,58534.24,3.00,4444,2024-05-26
27,ORD100027,HP Pavilion Laptop,Computers,HP,Souq,Giza,19624.30,1,19624.30,4.55,3542,2024-12-22
28,ORD100028,Bluetooth Headset,Accessories,JBL,Amazon,Giza,12094.71,2,24189.42,3.37,628,2024-08-28
29,ORD100029,Smartwatch FitPro,Wearables,FitPro,Jumia,Dubai,1682.41,2,3364.82,2.35,3355,2024-09-23
30,ORD100030,Samsung Galaxy A14,Electronics,Samsung,Jumia,Giza,6584.51,3,19753.53,1.02,4582,2024-09-07
31,ORD100031,HP Pavilion Laptop,Computers,HP,Souq,Giza,3760.61,2,7521.22,3.05,2947,2024-05-04
32,ORD100032,Dell Inspiron 3501,Computers,Dell,Amazon,Alexandria,15781.15,4,63124.60,2.04,4325,2024-08-08
33,ORD100033,Adidas Running Shoes,Fashion,Adidas,Souq,Alexandria,9205.93,2,18411.86,1.53,4684,2024-11-26
34,ORD100034,Adidas Running Shoes,Fashion,Adidas,Souq,Riyadh,8827.96,5,44139.80,2.22,1653,2024-04-26
35,ORD100035,iPhone 13,Electronics,Apple,Souq,Casablanca,3698.12,4,14792.48,4.00,4028,2024-06-22
36,ORD100036,iPhone 13,Electronics,Apple,Souq,Cairo,19025.22,2,38050.44,1.07,2108,2024-09-05
37,ORD100037,Bluetooth Headset,Accessories,JBL,Amazon,Alexandria,7460.49,5,37302.45,1.76,967,2024-10-16
38,ORD100038,Dell Inspiron 3501,Computers,Dell,Jumia,Dubai,8959.05,3,26877.15,3.54,3816,2024-09-08
39,ORD100039,Xiaomi Redmi Note 12,Electronics,Xiaomi,Jumia,Dubai,16159.36,4,64637.44,2.66,1433,2024-03-24
40,ORD100040,HP Pavilion Laptop,Computers,HP,Souq,Giza,14053.17,5,70265.85,2.92,2252,2024-02-19
41,ORD100041,Dell Inspiron 3501,Computers,Dell,Amazon,Casablanca,5551.93,5,27759.65,3.65,4041,2024-06-24
42,ORD100042,Xiaomi Redmi Note 12,Electronics,Xiaomi,Souq,Dubai,12852.91,4,51411.64,1.38,4551,2024-11-28
43,ORD100043,Nike Air Max,Fashion,Nike,Souq,Cairo,8129.36,5,40646.80,4.28,1636,2024-01-23
44,ORD100044,iPhone 13,Electronics,Apple,Jumia,Casablanca,8545.16,2,17090.32,1.57,3430,2024-10-15
45,ORD100045,Nike Air Max,Fashion,Nike,Jumia,Dubai,12387.97,4,49551.88,2.32,1568,2024-01-03
46,ORD100046,T-shirt Cotton,Fashion,Generic,Amazon,Giza,10278.34,1,10278.34,4.39,3827,2024-07-24
47,ORD100047,Nike Air Max,Fashion,Nike,Jumia,Giza,11576.04,5,57880.20,3.97,2789,2024-11-24
48,ORD100048,Xiaomi Redmi Note 12,Electronics,Xiaomi,Jumia,Casablanca,12112.14,3,36336.42,3.70,2088,2024-11-29
49,ORD100049,Xiaomi Redmi Note 12,Electronics,Xiaomi,Souq,Casablanca,2211.64,4,8846.56,1.88,1320,2024-05-10

In [43]:
data.tail(50)

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
9950,ORD109950,Dell Inspiron 3501,Computers,Dell,Souq,Cairo,12511.19,5,62555.95,2.31,4214,2024-06-21
9951,ORD109951,Dell Inspiron 3501,Computers,Dell,Souq,Riyadh,10031.07,1,10031.07,2.85,228,2024-03-19
9952,ORD109952,HP Pavilion Laptop,Computers,HP,Jumia,Dubai,16274.49,5,81372.45,3.40,4934,2024-10-18
9953,ORD109953,iPhone 13,Electronics,Apple,Jumia,Cairo,5275.50,5,26377.50,4.94,4329,2024-12-24
9954,ORD109954,Xiaomi Redmi Note 12,Electronics,Xiaomi,Amazon,Dubai,9192.68,4,36770.72,2.93,4002,2024-04-15
9955,ORD109955,Dell Inspiron 3501,Computers,Dell,Souq,Alexandria,17221.77,4,68887.08,1.69,2022,2024-09-28
9956,ORD109956,Xiaomi Redmi Note 12,Electronics,Xiaomi,Souq,Dubai,9182.09,4,36728.36,2.52,3144,2024-02-18
9957,ORD109957,Samsung Galaxy A14,Electronics,Samsung,Jumia,Dubai,14539.16,1,14539.16,4.41,428,2024-09-08
9958,ORD109958,iPhone 13,Electronics,Apple,Amazon,Cairo,12926.83,2,25853.66,4.20,1780,2024-12-12
9959,ORD109959,HP Pavilion Laptop,Computers,HP,Souq,Casablanca,10516.66,4,42066.64,2.43,2724,2024-11-04
9960,ORD109960,Smartwatch FitPro,Wearables,FitPro,Amazon,Alexandria,176.52,2,353.04,4.59,1723,2024-02-03
9961,ORD109961,Dell Inspiron 3501,Computers,Dell,Amazon,Cairo,8098.57,5,40492.85,1.39,3412,2024-10-31
9962,ORD109962,iPhone 13,Electronics,Apple,Jumia,Alexandria,8979.41,5,44897.05,1.18,494,2024-10-11
9963,ORD109963,Dell Inspiron 3501,Computers,Dell,Souq,Giza,12125.25,4,48501.00,3.88,250,2024-09-01
9964,ORD109964,Bluetooth Headset,Accessories,JBL,Jumia,Riyadh,18513.15,1,18513.15,1.28,4718,2024-08-22
9965,ORD109965,Xiaomi Redmi Note 12,Electronics,Xiaomi,Souq,Cairo,6134.45,2,12268.90,4.62,4834,2024-02-01
9966,ORD109966,HP Pavilion Laptop,Computers,HP,Amazon,Casablanca,3420.82,3,10262.46,3.61,1563,2024-05-13
9967,ORD109967,Xiaomi Redmi Note 12,Electronics,Xiaomi,Jumia,Cairo,13164.66,2,26329.32,3.65,3378,2024-02-17
9968,ORD109968,Dell Inspiron 3501,Computers,Dell,Jumia,Cairo,17620.82,4,70483.28,2.49,3124,2024-01-21
9969,ORD109969,Samsung Galaxy A14,Electronics,Samsung,Amazon,Cairo,5693.84,2,11387.68,4.23,1106,2024-07-12
9970,ORD109970,iPhone 13,Electronics,Apple,Souq,Alexandria,18829.33,2,37658.66,4.19,4472,2024-04-17
9971,ORD109971,HP Pavilion Laptop,Computers,HP,Jumia,Giza,18338.20,3,55014.60,4.67,1445,2024-11-22
9972,ORD109972,Smartwatch FitPro,Wearables,FitPro,Souq,Dubai,982.26,1,982.26,1.75,4638,2024-04-17
9973,ORD109973,Samsung Galaxy A14,Electronics,Samsung,Souq,Riyadh,12778.33,3,38334.99,1.75,1252,2024-07-05
9974,ORD109974,Bluetooth Headset,Accessories,JBL,Amazon,Alexandria,6865.56,1,6865.56,2.77,2092,2024-09-19
9975,ORD109975,Bluetooth Headset,Accessories,JBL,Souq,Dubai,4203.17,3,12609.51,3.46,3765,2024-02-29
9976,ORD109976,Samsung Galaxy A14,Electronics,Samsung,Souq,Alexandria,1136.86,3,3410.58,4.10,839,2024-02-09
9977,ORD109977,iPhone 13,Electronics,Apple,Amazon,Cairo,2675.05,1,2675.05,4.28,3215,2024-11-22
9978,ORD109978,Xiaomi Redmi Note 12,Electronics,Xiaomi,Amazon,Cairo,3850.47,1,3850.47,2.78,3581,2024-02-22
9979,ORD109979,Smartwatch FitPro,Wearables,FitPro,Souq,Giza,10315.05,1,10315.05,1.89,479,2024-04-26
9980,ORD109980,Nike Air Max,Fashion,Nike,Amazon,Dubai,15257.93,5,76289.65,3.67,2131,2024-02-19
9981,ORD109981,iPhone 13,Electronics,Apple,Jumia,Dubai,12830.85,2,25661.70,4.89,698,2024-01-10
9982,ORD109982,T-shirt Cotton,Fashion,Generic,Amazon,Dubai,6093.55,4,24374.20,1.54,3604,2024-09-19
9983,ORD109983,Dell Inspiron 3501,Computers,Dell,Amazon,Alexandria,7339.72,5,36698.60,1.82,3518,2024-02-11
9984,ORD109984,Adidas Running Shoes,Fashion,Adidas,Souq,Dubai,15847.46,5,79237.30,2.51,4700,2024-04-07
9985,ORD109985,iPhone 13,Electronics,Apple,Souq,Cairo,15329.04,5,76645.20,3.87,15,2024-10-30
9986,ORD109986,Samsung Galaxy A14,Electronics,Samsung,Souq,Dubai,18415.53,1,18415.53,2.01,2446,2024-01-09
9987,ORD109987,Nike Air Max,Fashion,Nike,Amazon,Casablanca,17139.83,2,34279.66,2.37,920,2024-06-13
9988,ORD109988,Dell Inspiron 3501,Computers,Dell,Amazon,Giza,9093.51,5,45467.55,4.08,4273,2024-11-10
9989,ORD109989,Bluetooth Headset,Accessories,JBL,Amazon,Casablanca,6882.22,5,34411.10,3.13,2771,2024-08-13
9990,ORD109990,Samsung Galaxy A14,Electronics,Samsung,Souq,Casablanca,3397.33,4,13589.32,1.37,370,2024-02-10
9991,ORD109991,iPhone 13,Electronics,Apple,Jumia,Alexandria,5108.58,5,25542.90,4.13,1586,2024-09-03
9992,ORD109992,Nike Air Max,Fashion,Nike,Jumia,Cairo,12745.76,3,38237.28,3.09,785,2024-06-14
9993,ORD109993,iPhone 13,Electronics,Apple,Souq,Casablanca,19530.95,4,78123.80,4.34,4356,2024-04-10
9994,ORD109994,Adidas Running Shoes,Fashion,Adidas,Jumia,Cairo,6384.43,3,19153.29,3.04,2551,2024-05-16
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

In [44]:
data

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

In [45]:
# do data manipulation - pandas 
# work on numbers - numpy

In [47]:
data.isnull().sum() ## to check missing values

OrderID        0
Product        0
Category       0
Brand          0
Platform       0
City           0
Price          0
Quantity       0
TotalAmount    0
Rating         0
Reviews        0
OrderDate      0
dtype: int64

In [48]:
# stastical analysis of data

In [57]:
data.describe() ##to see the statstical analysis

              Price      Quantity   TotalAmount        Rating       Reviews
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean   10027.986331      3.006200  30199.572439      3.005592   2520.072200
std     5728.261196      1.415472  23861.789828      1.154845   1443.849734
min      105.590000      1.000000    113.550000      1.000000      0.000000
25%     4999.862500      2.000000  11066.910000      2.010000   1275.000000
50%    10063.600000      3.000000  23671.630000      3.005000   2537.500000
75%    14938.430000      4.000000  44648.580000      4.000000   3767.000000
max    19999.340000      5.000000  99993.800000      5.000000   5000.000000

In [58]:
data.info() # to see the data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      10000 non-null  object
 1   Product      10000 non-null  object
 2   Category     10000 non-null  object
 3   Brand        10000 non-null  object
 4   Platform     10000 non-null  object
 5   City         10000 non-null  object
 6   Price        10000 non-null  float64
 7   Quantity     10000 non-null  int64
 8   TotalAmount  10000 non-null  float64
 9   Rating       10000 non-null  float64
 10  Reviews      10000 non-null  int64
 11  OrderDate    10000 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 937.6+ KB

In [61]:
# when you are making any project in python
## data linraries (numpy , pandas -- relevant to your anlysis import 
## data cleaning -- remove of missing values and filling them with approritate mesaure ,
##duplicate removal , outliers remoavl , standarization of data 
## data analysis -- finding insights out of data 
## data visualization -- plotting of charts , colums etc 
## machine learning and recommendation systems -- prediction , predcitve modelling

In [62]:
data

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

## DATA CLEANING

In [66]:
## Mising values

In [67]:
data.isnull().sum()

OrderID        0
Product        0
Category       0
Brand          0
Platform       0
City           0
Price          0
Quantity       0
TotalAmount    0
Rating         0
Reviews        0
OrderDate      0
dtype: int64

In [68]:
## to check duplicates

In [71]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [72]:
## in duplicate false means there are no duplicate true means duplicates

In [73]:
data

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

#EDA

In [74]:
# to find most selling product based on product id

In [88]:
data=pd.read_csv("ecommerce_10000.csv")

In [89]:
data

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD109995,HP Pavilion Laptop,Computers,HP,Jumia,Riyadh,3571.93,1,3571.93,1.05,2154,2024-05-21
9996,ORD109996,Adidas Running Shoes,Fashion,Adidas,Souq,Cairo,2974.55,4,11898.20,2.60,1796,2024-11-27
9997,ORD109997,Adidas Running Shoes,Fashion,Adidas,Amazon,Riyadh,8646.20,1,8646.20,3.20,4001,2024-10-15
9998,ORD109998,T-shirt Cotton,Fashion,Generic,Amazon,Riyadh,4960.53,4,19842.12,3.42,685,2024-04-26
9999,ORD109999,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,13811.49,5,69057.45,2.84,488,2024-01-15

In [90]:
## EDA

In [91]:
##finding most selling product based on order id

In [92]:
data.groupby("OrderID")["TotalAmount"].sum()

OrderID
ORD100000    16284.02
ORD100001    13290.40
ORD100002    26648.76
ORD100003     3665.44
ORD100004    10420.74
               ...
ORD109995     3571.93
ORD109996    11898.20
ORD109997     8646.20
ORD109998    19842.12
ORD109999    69057.45
Name: TotalAmount, Length: 10000, dtype: float64

In [93]:
## to check how many products are there per order

In [96]:
data.groupby("Product")["OrderID"].count()

Product
Adidas Running Shoes     968
Bluetooth Headset       1029
Dell Inspiron 3501       962
HP Pavilion Laptop       991
Nike Air Max            1005
Samsung Galaxy A14      1043
Smartwatch FitPro       1020
T-shirt Cotton           997
Xiaomi Redmi Note 12    1030
iPhone 13                955
Name: OrderID, dtype: int64

In [98]:
## to fund the highest selling product based on total amount

In [103]:
a=data.groupby("Product")["TotalAmount"].sum()

In [104]:
a

Product
Adidas Running Shoes    30269021.82
Bluetooth Headset       29200970.13
Dell Inspiron 3501      28060270.42
HP Pavilion Laptop      29482727.14
Nike Air Max            30727637.51
Samsung Galaxy A14      30004263.23
Smartwatch FitPro       31420413.20
T-shirt Cotton          30507500.40
Xiaomi Redmi Note 12    33772598.37
iPhone 13               28550322.17
Name: TotalAmount, dtype: float64

In [106]:
top_product=a.idxmax()

In [107]:
top_product

'Xiaomi Redmi Note 12'

In [108]:
## which brand is most selling and which brand is least selling

In [137]:
brand=data.groupby("Brand")["TotalAmount"].sum().sort_values(ascending=False)

In [138]:
brand

Brand
Xiaomi     33772598.37
FitPro     31420413.20
Nike       30727637.51
Generic    30507500.40
Adidas     30269021.82
Samsung    30004263.23
HP         29482727.14
JBL        29200970.13
Apple      28550322.17
Dell       28060270.42
Name: TotalAmount, dtype: float64

In [120]:
## sort data in asc and desc order in python

In [129]:
## converting brand into a dataframe

In [131]:
brand_df=data[["Brand"]]
print(brand_df)

        Brand
0     Samsung
1        Nike
2         JBL
3          HP
4       Apple
...       ...
9995       HP
9996   Adidas
9997   Adidas
9998  Generic
9999      JBL

[10000 rows x 1 columns]