# Data Analysis NYKAA MARKETING

# loading basic libraries

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

# Data Loading and pre analysis

In [2]:
df=pd.read_csv("nykaa_campaign_data.csv")

In [3]:
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,30-05-2025

In [5]:
df.shape

(55555, 16)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  object
 1   Campaign_Type     55555 non-null  object
 2   Target_Audience   55555 non-null  object
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  object
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  object
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  object
 15  Date              55555 non-null  object
dtypes: float64(3), int64(6), object(7)
memory usage: 6.8+ MB

In [9]:
df.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,55555.000000,55555.000000,55555.000000,55555.000000,55555.000000,5.555500e+04,55555.000000,55555.000000,55555.000000
mean,17.446044,55087.885357,4688.070507,1877.271119,1032.866925,5.158197e+05,377.347068,2.713807,13.784169
std,7.520438,25930.001514,3178.686285,1435.636117,862.496788,4.900121e+05,541.084524,4.493380,6.353125
min,5.000000,10001.000000,202.000000,56.000000,19.000000,6.183000e+03,9.080000,-0.970000,2.600000
25%,11.000000,32680.000000,2110.000000,779.000000,400.000000,1.777060e+05,105.435000,0.040000,8.360000
50%,17.000000,55182.000000,3907.000000,1481.000000,779.000000,3.604360e+05,207.510000,1.240000,13.600000
75%,24.000000,77514.500000,6688.000000,2605.000000,1414.000000,6.874225e+05,428.580000,3.630000,18.855000
max,30.000000,100000.000000,14868.000000,8876.000000,6686.000000,4.579910e+06,15473.160000,74.420000,30.910000

In [11]:
df['Revenue'].describe() # to see a single column

count    5.555500e+04
mean     5.158197e+05
std      4.900121e+05
min      6.183000e+03
25%      1.777060e+05
50%      3.604360e+05
75%      6.874225e+05
max      4.579910e+06
Name: Revenue, dtype: float64

# Data Cleaning

In [18]:
misisng_values=df.isnull()

In [19]:
misisng_values

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55551,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55552,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55553,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55554,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df.isnull()

Campaign_ID         0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Impressions         0
Clicks              0
Leads               0
Conversions         0
Revenue             0
Acquisition_Cost    0
ROI                 0
Language            0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [20]:
## df.sum.isnull()

In [21]:
## to see the duplicate values

In [22]:
df.columns

Index(['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration',
       'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions',
       'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score',
       'Customer_Segment', 'Date'],
      dtype='object')

In [24]:
df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [25]:
## checking duplicates

In [30]:
df.duplicated('Campaign_ID')

0        False
1        False
2        False
3        False
4        False
         ...
55550    False
55551    False
55552    False
55553    False
55554    False
Length: 55555, dtype: bool

In [31]:
import pandas as dp

In [32]:
dp.read_csv("nykaa_campaign_data.csv")

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,30-05-2025

# what are outliers and how to remove it

In [34]:
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,30-05-2025

In [35]:
## outliers are your numbers or values that are odd which changes the averages

# Outliers

# an outlier is a value in your data that is very different from most of the other values for ex : 20000, 3000,  80000 in this case 800000 is the outlier

# IQR (inter-quartile range) : it is a way to measure the middle spread of your data 
we have 3 key points here :
q1 (25th percentile)- 25% of data below this 
q2=median middle value 
q3=75th percnetile = 75% of data below this 

IQR=Q3-Q1
it tells you spread of the middle 50% of the data 

how iQR HELP IN FINDING OUTLIERS 

we have boundaries here to define = lower limit = q1-1.5*IQR 
UPPER LIMIT : Q3+1.5*IQR 

any value which is outside this range = outlier

it can only be used to check in numerical columns

In [41]:
Q1=df['Revenue'].quantile(0.25)
Q3=df['Revenue'].quantile(0.75)
IQR=Q3-Q1
outliers =df[(df['Revenue']<Q1-1.5*IQR)|(df['Revenue']+1.5*IQR)]

In [43]:
outliers

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,30-05-2025

In [44]:
outliers.shape

(55555, 16)

In [47]:
Q1=df['ROI'].quantile(0.25)
Q3=df['ROI'].quantile(0.75)
IQR=Q3-Q1
different =df[(df['ROI']<Q1-1.5*IQR)|(df['ROI']+1.5*IQR)]

In [48]:
different

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,30-05-2025

In [49]:
import pandas as pd
data={
    'company':['A','B','C','D','E','F','G','H'],
    'revenue':[100,120,130,110,115,500,125,105]
}
df=pd.DataFrame(data)
df

  company  revenue
0       A      100
1       B      120
2       C      130
3       D      110
4       E      115
5       F      500
6       G      125
7       H      105

In [52]:
# apply IQR 
Q1=df['revenue'].quantile(0.25)
Q3=df['revenue'].quantile(0.75)
IOR=Q3-Q1

In [53]:
IQR

np.float64(3.59)

In [54]:
# detecting outliers

In [56]:
outliers=df[(df['revenue']<Q1-1.5*IQR)|(df['revenue']>Q3+1.5*IQR)]
outliers

  company  revenue
0       A      100
5       F      500

In [58]:
df

  company  revenue
0       A      100
1       B      120
2       C      130
3       D      110
4       E      115
5       F      500
6       G      125
7       H      105

In [59]:
df=pd.read_csv("nykaa_campaign_data.csv")

In [60]:
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,30-05-2025

In [61]:
Q1=df['Duration'].quantile(0.25)
Q3=df['Duration'].quantile(0.75)
IOR=Q3-Q1

In [62]:
IQR # this never changes

np.float64(3.59)

In [63]:
outliers=df[(df['Duration']<Q1-1.5*IQR)|(df['Duration']>Q3+1.5*IQR)]
outliers

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
10,NY-CMP-1010,SEO,Working Women,5,"Google, Instagram",59141,1556,580,221,121550,357.66,0.54,Hindi,3.99,Working Women,26-10-2024
14,NY-CMP-1014,Paid Ads,Premium Shoppers,5,Instagram,38072,2591,1542,769,240697,369.75,-0.15,Bengali,12.88,College Students,06-07-2024
43,NY-CMP-1043,Influencer,Premium Shoppers,30,YouTube,37002,2753,979,780,371280,123.02,2.87,Tamil,12.19,College Students,29-05-2025
47,NY-CMP-1047,Social Media,College Students,5,YouTube,14944,1268,482,318,104304,319.84,0.03,Hindi,13.84,Working Women,02-04-2025
50,NY-CMP-1050,Paid Ads,Working Women,30,"WhatsApp, Facebook",67932,9449,5194,3230,839800,33.28,6.81,English,26.31,Working Women,04-11-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55472,NY-CMP-56472,Influencer,Premium Shoppers,5,"WhatsApp, Facebook, Instagram",92293,6976,4084,2287,1424801,78.99,6.89,English,14.46,Tier 2 City Customers,13-04-2025
55481,NY-CMP-56481,Social Media,Premium Shoppers,5,YouTube,58387,7836,3976,2452,1902752,103.55,6.49,English,24.43,Premium Shoppers,09-06-2025
55502,NY-CMP-56502,Influencer,College Students,5,"Google, Email",76032,1651,961,654,337464,89.55,4.76,English,4.30,Tier 2 City Customers,30-08-2024
55539,NY-CMP-56539,Social Media,Working Women,30,YouTube,57169,4953,2100,702,403650,217.47,1.64,English,13.57,Premium Shoppers,04-10-2024
55549,NY-CMP-56549,Influencer,Tier 2 City Customers,30,"YouTube, Google, Instagram",51879,7200,3153,2459,1795070,82.21,7.88,Tamil,24.70,Working Women,11-05-2025

# EDA

In [65]:
data=df.groupby('Campaign_Type')['Impressions'].max()

In [66]:
data

Campaign_Type
Email            99985
Influencer      100000
Paid Ads         99992
SEO             100000
Social Media     99995
Name: Impressions, dtype: int64

In [67]:
data=df.groupby('Campaign_Type')['Revenue'].max().sort_values(ascending=False).head(5)

In [68]:
data

Campaign_Type
Paid Ads        4579910
SEO             4412709
Influencer      4326120
Email           4119352
Social Media    3641385
Name: Revenue, dtype: int64