In [1]:
import numpy as np 
import pandas as pd

In [2]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_typing', '_using_numpy2_behavior', '_utils', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split', 'array_str', 'asanyarray', 'asarray', 'asarray_chkfinite', 'ascontiguousarray', 'asfarray', 'asfortranarray', 'asmatrix', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'average', 'bartlett', 'base_repr', 'binary_repr', 'bincount', 'bitwise_and', 'bitwise_not', 'bitwise_or', 'bitwise_xor', 'blackman', 'block', 'bmat', 'bool_', 'broadcast', 'broadcast_arrays', 'broadcast_shapes', 'broadcast_to', 'busday_count', 'busday_offset', 'busdaycalendar', 'byte', 'byte_bounds', 'bytes_', 'c_', 'can_cast', 'cast', 'cbrt', 'cdouble', 'ceil', 'cfloat', 'char', 'character', 'chararray', 'choose', 'clip', 'clongdouble', 'clongfloat', 'column_stack', 'common_type', 'compare_chararrays', 'compat', 'complex128', 'complex64', 'complex_', 'complexfloating', 'compress', 'concatenate', 'conj', 'conjugate', 'convolve', 'copy', 'copysign', 'copyto', 'corrcoef', 'correlate', 'cos', 'cosh', 'count_nonzero', 'cov', 'cross', 'csingle', 'ctypeslib', 'cumprod', 'cumproduct', 'cumsum', 'datetime64', 'datetime_as_string', 'datetime_data', 'deg2rad', 'degrees', 'delete', 'deprecate', 'deprecate_with_doc', 'diag', 'diag_indices', 'diag_indices_from', 'diagflat', 'diagonal', 'diff', 'digitize', 'disp', 'divide', 'divmod', 'dot', 'double', 'dsplit', 'dstack', 'dtype', 'dtypes', 'e', 'ediff1d', 'einsum', 'einsum_path', 'emath', 'empty', 'empty_like', 'equal', 'errstate', 'euler_gamma', 'exceptions', 'exp', 'exp2', 'expand_dims', 'expm1', 'expm1x', 'extract', 'eye', 'fabs', 'fastCopyAndTranspose', 'fft', 'fill_diagonal', 'find_common_type', 'finfo', 'fix', 'flatiter', 'flatnonzero', 'flexible', 'flip', 'fliplr', 'flipud', 'float16', 'float32', 'float64', 'float_', 'float_power', 'floating', 'floor', 'floor_divide', 'fmax', 'fmin', 'fmod', 'format_float_positional', 'format_float_scientific', 'format_parser', 'frexp', 'from_dlpack', 'frombuffer', 'fromfile', 'fromfunction', 'fromiter', 'frompyfunc', 'fromregex', 'fromstring', 'full', 'full_like', 'gcd', 'generic', 'genfromtxt', 'geomspace', 'get_array_wrap', 'get_include', 'get_printoptions', 'getbufsize', 'geterr', 'geterrcall', 'geterrobj', 'gradient', 'greater', 'greater_equal', 'half', 'hamming', 'hanning', 'heaviside', 'histogram', 'histogram2d', 'histogram_bin_edges', 'histogramdd', 'hsplit', 'hstack', 'hypot', 'i0', 'identity', 'iinfo', 'imag', 'in1d', 'index_exp', 'indices', 'inexact', 'inf', 'info', 'infty', 'inner', 'insert', 'int16', 'int32', 'int64', 'int8', 'int_', 'intc', 'integer', 'interp', 'intersect1d', 'intp', 'invert', 'is_busday', 'isclose', 'iscomplex', 'iscomplexobj', 'isfinite', 'isfortran', 'isin', 'isinf', 'isnan', 'isnat', 'isneginf', 'isposinf', 'isreal', 'isrealobj', 'isscalar', 'issctype', 'issubclass_', 'issubdtype', 'issubsctype', 'iterable', 'ix_', 'kaiser', 'kron', 'lcm', 'ldexp', 'left_shift', 'less', 'less_equal', 'lexsort', 'lib', 'linalg', 'linspace', 'little_endian', 'load', 'loadtxt', 'log', 'log10', 'log1p', 'log2', 'logaddexp', 'logaddexp2', 'logical_and', 'logical_not', 'logical_or', 'logical_xor', 'logspace', 'longcomplex', 'longdouble', 'longfloat', 'longlong', 'lookfor', 'ma', 'mask_indices', 'mat', 'matmul', 'matrix', 'max', 'maximum', 'maximum_sctype', 'may_share_memory', 'mean', 'median', 'memmap', 'meshgrid', 'mgrid', 'min', 'min_scalar_type', 'minimum', 'mintypecode', 'mod', 'modf', 'moveaxis', 'msort', 'multiply', 'nan', 'nan_to_num', 'nanargmax', 'nanargmin', 'nancumprod', 'nancumsum', 'nanmax', 'nanmean', 'nanmedian', 'nanmin', 'nanpercentile', 'nanprod', 'nanquantile', 'nanstd', 'nansum', 'nanvar', 'nbytes', 'ndarray', 'ndenumerate', 'ndim', 'ndindex', 'nditer', 'negative', 'nested_iters', 'newaxis', 'nextafter', 'nonzero', 'not_equal', 'numarray', 'number', 'obj2sctype', 'object_', 'ogrid', 'oldnumeric', 'ones', 'ones_like', 'outer', 'packbits', 'pad', 'partition', 'percentile', 'pi', 'piecewise', 'place', 'poly', 'poly1d', 'polyadd', 'polyder', 'polydiv', 'polyfit', 'polyint', 'polymul', 'polynomial', 'polysub', 'polyval', 'positive', 'power', 'printoptions', 'prod', 'product', 'promote_types', 'ptp', 'put', 'put_along_axis', 'putmask', 'quantile', 'r_', 'rad2deg', 'radians', 'random', 'ravel', 'ravel_multi_index', 'real', 'real_if_close', 'rec', 'recarray', 'recfromcsv', 'recfromtxt', 'reciprocal', 'record', 'remainder', 'repeat', 'require', 'reshape', 'resize', 'result_type', 'right_shift', 'rint', 'roll', 'rollaxis', 'roots', 'rot90', 'round', 'round_', 'row_stack', 's_', 'safe_eval', 'save', 'savetxt', 'savez', 'savez_compressed', 'sctype2char', 'sctypeDict', 'sctypes', 'searchsorted', 'select', 'set_numeric_ops', 'set_printoptions', 'set_string_function', 'setbufsize', 'setdiff1d', 'seterr', 'seterrcall', 'seterrobj', 'setxor1d', 'shape', 'shares_memory', 'short', 'show_config', 'show_runtime', 'sign', 'signbit', 'signedinteger', 'sin', 'sinc', 'single', 'singlecomplex', 'sinh', 'size', 'sometrue', 'sort', 'sort_complex', 'source', 'spacing', 'split', 'sqrt', 'square', 'squeeze', 'stack', 'std', 'str_', 'string_', 'subtract', 'sum', 'swapaxes', 'take', 'take_along_axis', 'tan', 'tanh', 'tensordot', 'test', 'testing', 'tile', 'timedelta64', 'trace', 'tracemalloc_domain', 'transpose', 'trapz', 'tri', 'tril', 'tril_indices', 'tril_indices_from', 'trim_zeros', 'triu', 'triu_indices', 'triu_indices_from', 'true_divide', 'trunc', 'typecodes', 'typename', 'ubyte', 'ufunc', 'uint', 'uint16', 'uint32', 'uint64', 'uint8', 'uintc', 'uintp', 'ulonglong', 'unicode_', 'union1d', 'unique', 'unpackbits', 'unravel_index', 'unsignedinteger', 'unwrap', 'ushort', 'vander', 'var', 'vdot', 'vectorize', 'version', 'void', 'vsplit', 'vstack', 'where', 'who', 'zeros', 'zeros_like']

In [4]:
a=10,20,30,40
np.sum(a)

100

In [6]:
data=pd.read_excel("Online Sales Data.xlsx")

In [7]:
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [8]:
data=pd.read_csv("retail.csv")

In [9]:
data

,Order_Date,Country,City,Category,Sub_Category,Segment,Sales_Channel,Payment_Mode,Sales,Quantity,Discount,Profit
0,2022-06-20,UAE,Dubai,Furniture,Snacks,Consumer,Offline,UPI,2555.49,11,0.08,255.37
1,2023-12-05,UK,London,Sports,Phones,Home Office,Online,Net Banking,1795.27,9,0.28,-332.23
2,2022-07-05,USA,Los Angeles,Electronics,Shirts,Consumer,Offline,UPI,4554.73,10,0.13,140.24
3,2024-10-05,USA,New York,Furniture,Phones,Consumer,Online,Net Banking,3107.15,13,0.14,60.70
4,2023-07-21,USA,New York,Beauty,Fitness,Consumer,Offline,Card,2781.45,12,0.20,61.78
...,...,...,...,...,...,...,...,...,...,...,...,...
1595,2023-10-17,Canada,Toronto,Furniture,Snacks,Home Office,Offline,Net Banking,4219.78,5,0.24,1475.43
1596,2021-04-16,France,Lyon,Clothing,Fitness,Corporate,Online,Net Banking,2036.60,7,0.24,382.78
1597,2021-06-11,Australia,Sydney,Sports,Cosmetics,Home Office,Offline,UPI,3705.21,3,0.18,-95.61
1598,2024-05-21,India,Mumbai,Electronics,Snacks,Corporate,Offline,Cash,4526.83,12,0.25,-127.08
1599,2021-07-25,India,Bangalore,Electronics,Snacks,Consumer,Online,UPI,673.35,14,0.27,-100.56

In [10]:
data=pd.read_excel("C:\Users\asus\Downloads\Online Sales Data.xlsx")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1787595858.py, line 1)

In [11]:
data=pd.read_excel("C:\\Users\\asus\\Downloads\\Online Sales Data.xlsx")

In [12]:
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

### Functions in numpy 
## Functions are inbuilt or predefined piece of information that performs operations on a specific task

## functions in numpy : in numpy it is a predefined piece of code that performs a specific operation on number , arrays , metrices instead of writting calculation from scracth

## important functions in numpy and their use :
## in numpy functions are used to work on numbers 
## arrray correaltion functions :'
## array : it is a linear data strucutre that store homogenous(Same type of data )
## correlation : to show how change in one variable impact other

In [14]:
##array correaltion function

## np.array(): create arrays from lists or tuples

In [19]:
import numpy as np 
arr=np.array([1,2,3,4])

In [20]:
arr

array([1, 2, 3, 4])

In [21]:
##np.arange: generate a range of values

In [25]:
np.arange(0,10,2)# we are using 2 here to have a difference of two to geenrate numbers

array([0, 2, 4, 6, 8])

In [26]:
#np.arange: use case : it is used when we create sequences like time steps or indices (0,1,2,4,5....?)

In [27]:
#np.linspace: generate evenly spaced numbers

In [29]:
np.linspace(0,5) # to give the linspace between characters or numbers and useful in plotting

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

# array shape & manipulation

In [31]:
# array shape and maipulation : it is used to identify shape of data and manipulate numbers in data

In [32]:
#np.resahpe(): changes shape of array

In [34]:
arr=np.arange(6)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
# to prepare data for models and matrices operations

In [36]:
## transpose : swaping rows and colums : columns swap to rows and rows to columns

In [37]:
arr=np.array([[1,2],[3,4]])
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [38]:
## required in linear algebra or feature engineering :
## feature engineering : when we want to generate a new columns based on data

## mathematical operations

In [39]:
#mean: to find average of data 
np.mean([1,2,3,4])

2.5

In [40]:
# np.sum-- to find sum of numbers 
np.sum([1,2,3])

6

In [48]:
##np.std()-- std devaition ## to find veraiability between numbers 
np.std([1,2,3,4])

1.118033988749895

In [49]:
np.product([1,2,3,4])

24

In [57]:
a=np.arange(0,10)
b=np.arange(0,10)
result=a-b

In [58]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
#statistical & aggreagtion functions

In [61]:
##np.min and np.max

In [62]:
np.min([3,1,5])

1

In [63]:
np.max([3,1,5])

5

In [64]:
#np.percentile--outliers use case : median , quartiles and distribution analysis

In [65]:
np.percentile([1,2,3,4,5],50)

3.0

In [66]:
## pandas functions

In [67]:
## data creation and loading in pandas

In [68]:
import pandas as pd

In [69]:
data={'name':['A','B'],'Age':[25,30]}
df=pd.DataFrame(data)

In [70]:
df

  name  Age
0    A   25
1    B   30

In [71]:
## if it has one column it is series in pandas and if it has more than 2 columns it is a dataframe

In [73]:
a=[10,20,'anshu',2.3]
a

[10, 20, 'anshu', 2.3]

In [74]:
## to read the data from type of file 
## read_csv- to read csv file 
##read.xlsx- to read excel file

In [75]:
## data inspection

In [76]:
##to see number of rows in the data

In [77]:
## head : to show the starting rows of data 
## tail : to show ending rows of data

In [85]:
df.head()

  name  Age
0    A   25
1    B   30

In [83]:
## by deafult head shows first 5 rows and tail shows last 5 rows

In [86]:
df.tail()

  name  Age
0    A   25
1    B   30

In [87]:
## df.info() -- check data types and missinf values in the data

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [89]:
## df.describe()-- summary of data (Stastical summary (mean , std,median etc)

In [90]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [91]:
## selection of data

In [94]:
##column selection :
df['Age']

0    25
1    30
Name: Age, dtype: int64

In [99]:
df[['name','Age']]

  name  Age
0    A   25
1    B   30

In [100]:
df

  name  Age
0    A   25
1    B   30

In [101]:
# df.loc

In [102]:
# label based 
df.loc[0,'name']

'A'

In [110]:
## iloc : iloc is position based ir extract specifc rows /columns 
df.iloc[1,0]

'B'

In [105]:
##it is used to extract specific rows

In [106]:
## filtering /sorting of data

In [111]:
## use case : get subset of data based on conditions

In [112]:
df[df['Age']>25]

  name  Age
1    B   30

In [113]:
## adding /modifying columns

In [114]:
df['salary']=[50000,70000]

In [115]:
df

  name  Age  salary
0    A   25   50000
1    B   30   70000

## salary column basis we find to bonus and want to create a new column this is called feature engineering that based on one feature or column in data we are create new feature/column

In [118]:
df['Bonus']=df['salary']*0.3

In [119]:
df['Bonus']

0    15000.0
1    21000.0
Name: Bonus, dtype: float64

In [121]:
df

  name  Age  salary    Bonus
0    A   25   50000  15000.0
1    B   30   70000  21000.0

In [122]:
## data cleaning

In [123]:
## handling missing data

In [124]:
##if data is missing 
df.isnull()

    name    Age  salary  Bonus
0  False  False   False  False
1  False  False   False  False

In [125]:
##if false no data is missing if true data is missing

In [126]:
## df.dropna()-- this is used to drop null values in data

In [128]:
df.dropna()

  name  Age  salary    Bonus
0    A   25   50000  15000.0
1    B   30   70000  21000.0

In [129]:
## to fill null values or replace

#df.fillna(0)## to repalce null values ## if the column is numerical then null value is replaced by mean if its is categroical then depends on data

In [131]:
## grouping and aggreagtion

In [132]:
## group by : analyse data by catagory

In [133]:
## sorting : to sort the data

In [134]:
## group by :
## df.grouby('department')['salary'].mean()
## sorting : df.sort_values(by='Age')-- descending to ascending (default)

## data loading

In [135]:
import numpy as np 
import pandas as pd

In [137]:
data=pd.read_excel("Online Sales Data.xlsx")

In [138]:
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

## data inspection

In [139]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    datetime64[ns]
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 17.0+ KB

In [140]:
data.describe()

,Transaction ID,Date,Units Sold,Unit Price,Total Revenue
count,240.00000,240,240.000000,240.000000,240.000000
mean,10120.50000,2024-04-29 12:00:00,2.158333,236.395583,335.699375
min,10001.00000,2024-01-01 00:00:00,1.000000,6.500000,6.500000
25%,10060.75000,2024-02-29 18:00:00,1.000000,29.500000,62.965000
50%,10120.50000,2024-04-29 12:00:00,2.000000,89.990000,179.970000
75%,10180.25000,2024-06-28 06:00:00,3.000000,249.990000,399.225000
max,10240.00000,2024-08-27 00:00:00,10.000000,3899.990000,3899.990000
std,69.42622,NaN,1.322454,429.446695,485.804469

#data cleaning

In [141]:
## finding missing values

In [142]:
data.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [145]:
data.duplicated() ## fist column by default

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [144]:
##data analysis

In [147]:
data.head(20)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card
10,10011,2024-01-11,Beauty Products,Chanel No. 5 Perfume,1,129.99,129.99,Europe,PayPal
11,10012,2024-01-12,Sports,Babolat Pure Drive Tennis Racket,3,199.99,599.97,Asia,Credit Card
12,10013,2024-01-13,Electronics,Samsung Galaxy Tab S8,2,749.99,1499.98,North America,Credit Card
13,10014,2024-01-14,Home Appliances,Keurig K-Elite Coffee Maker,1,189.99,189.99,Europe,PayPal
14,10015,2024-01-15,Clothing,North Face Down Jacket,2,249.99,499.98,Asia,Debit Card
15,10016,2024-01-16,Books,"Salt, Fat, Acid, Heat by Samin Nosrat",3,35.99,107.97,North America,Credit Card
16,10017,2024-01-17,Beauty Products,Dyson Supersonic Hair Dryer,1,399.99,399.99,Europe,PayPal
17,10018,2024-01-18,Sports,Manduka PRO Yoga Mat,4,119.99,479.96,Asia,Credit Card
18,10019,2024-01-19,Electronics,Garmin Forerunner 945,2,499.99,999.98,North America,Credit Card
19,10020,2024-01-20,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal

In [149]:
data.tail(4)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

##analysis

In [150]:
##top 5 product category based on revenue

In [151]:
top5=data.groupby('Product Category')['Total Revenue'].sum().nlargest(5)

In [152]:
top5

Product Category
Electronics        34982.41
Home Appliances    18646.16
Sports             14326.52
Clothing            8128.93
Beauty Products     2621.90
Name: Total Revenue, dtype: float64

In [153]:
top5=data.groupby('Product Category')['Total Revenue'].sum().nsmallest(5)

In [154]:
top5

Product Category
Books               1861.93
Beauty Products     2621.90
Clothing            8128.93
Sports             14326.52
Home Appliances    18646.16
Name: Total Revenue, dtype: float64