In [5]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv("Online-eCommerce.csv")

In [7]:
data

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,144464.0,TN,Rahul Kumar Prajapati,31/12/2022,Delivered,406 GB SSD,SSD,Samsung,4500.0,5850.0,1.0,4500.0,5850.0,Ajay Sharma
5106,144465.0,TR,Sagar Jeur,31/12/2022,Shipped,Intel i3 11th gen.,CPU,Intel,8500.0,11050.0,4.0,34000.0,44200.0,Roshan Kumar
5107,144466.0,UK,Rhushikesh Mane,31/12/2022,Order,4GB Graphic card,Graphic Card,Nvidia,12500.0,16250.0,2.0,25000.0,32500.0,Aarvi Gupta
5108,144467.0,UP,Ashish Kumar,31/12/2022,Processing,158 GB DDR4 RAM,RAM,Hynix,3500.0,4550.0,2.0,7000.0,9100.0,Vijay Singh
5109,144468.0,WB,Javed Akhter,31/12/2022,Delivered,BTX motherboard,Motherboard,Gigabyte,4500.0,5850.0,3.0,13500.0,17550.0,Aadil Khan

#data loading and prepartion

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Number         5095 non-null   float64
 1   State_Code           5095 non-null   object
 2   Customer_Name        5095 non-null   object
 3   Order_Date           5095 non-null   object
 4   Status               5095 non-null   object
 5   Product              5095 non-null   object
 6   Category             5095 non-null   object
 7   Brand                5095 non-null   object
 8   Cost                 5095 non-null   float64
 9   Sales                5095 non-null   float64
 10  Quantity             5095 non-null   float64
 11  Total_Cost           5095 non-null   float64
 12  Total_Sales          5095 non-null   float64
 13  Assigned Supervisor  5095 non-null   object
dtypes: float64(6), object(8)
memory usage: 559.0+ KB

In [9]:
data.describe()

,Order_Number,Cost,Sales,Quantity,Total_Cost,Total_Sales
count,5095.000000,5095.000000,5095.000000,5095.000000,5095.000000,5095.000000
mean,141921.000000,6066.123651,7885.960746,2.486948,14991.778214,19489.311678
std,1470.944141,3952.022039,5137.628651,1.113581,12574.918427,16347.393955
min,139374.000000,350.000000,455.000000,1.000000,350.000000,455.000000
25%,140647.500000,2100.000000,2730.000000,2.000000,4500.000000,5850.000000
50%,141921.000000,6550.000000,8515.000000,2.000000,10720.000000,13936.000000
75%,143194.500000,8500.000000,11050.000000,3.000000,22950.000000,29835.000000
max,144468.000000,14500.000000,18850.000000,4.000000,58000.000000,75400.000000

In [10]:
## null values

In [11]:
data.isnull().sum()

Order_Number           15
State_Code             15
Customer_Name          15
Order_Date             15
Status                 15
Product                15
Category               15
Brand                  15
Cost                   15
Sales                  15
Quantity               15
Total_Cost             15
Total_Sales            15
Assigned Supervisor    15
dtype: int64

In [12]:
data.isnull()

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5106,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5107,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5108,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5109,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
data[data.isnull().any(axis=1)]

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
## deleting all the rows with null values

In [15]:
data.dropna()

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,144464.0,TN,Rahul Kumar Prajapati,31/12/2022,Delivered,406 GB SSD,SSD,Samsung,4500.0,5850.0,1.0,4500.0,5850.0,Ajay Sharma
5106,144465.0,TR,Sagar Jeur,31/12/2022,Shipped,Intel i3 11th gen.,CPU,Intel,8500.0,11050.0,4.0,34000.0,44200.0,Roshan Kumar
5107,144466.0,UK,Rhushikesh Mane,31/12/2022,Order,4GB Graphic card,Graphic Card,Nvidia,12500.0,16250.0,2.0,25000.0,32500.0,Aarvi Gupta
5108,144467.0,UP,Ashish Kumar,31/12/2022,Processing,158 GB DDR4 RAM,RAM,Hynix,3500.0,4550.0,2.0,7000.0,9100.0,Vijay Singh
5109,144468.0,WB,Javed Akhter,31/12/2022,Delivered,BTX motherboard,Motherboard,Gigabyte,4500.0,5850.0,3.0,13500.0,17550.0,Aadil Khan

In [16]:
data.isnull().sum()

Order_Number           15
State_Code             15
Customer_Name          15
Order_Date             15
Status                 15
Product                15
Category               15
Brand                  15
Cost                   15
Sales                  15
Quantity               15
Total_Cost             15
Total_Sales            15
Assigned Supervisor    15
dtype: int64

In [17]:
data.dropna()

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,144464.0,TN,Rahul Kumar Prajapati,31/12/2022,Delivered,406 GB SSD,SSD,Samsung,4500.0,5850.0,1.0,4500.0,5850.0,Ajay Sharma
5106,144465.0,TR,Sagar Jeur,31/12/2022,Shipped,Intel i3 11th gen.,CPU,Intel,8500.0,11050.0,4.0,34000.0,44200.0,Roshan Kumar
5107,144466.0,UK,Rhushikesh Mane,31/12/2022,Order,4GB Graphic card,Graphic Card,Nvidia,12500.0,16250.0,2.0,25000.0,32500.0,Aarvi Gupta
5108,144467.0,UP,Ashish Kumar,31/12/2022,Processing,158 GB DDR4 RAM,RAM,Hynix,3500.0,4550.0,2.0,7000.0,9100.0,Vijay Singh
5109,144468.0,WB,Javed Akhter,31/12/2022,Delivered,BTX motherboard,Motherboard,Gigabyte,4500.0,5850.0,3.0,13500.0,17550.0,Aadil Khan

In [18]:
data

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,144464.0,TN,Rahul Kumar Prajapati,31/12/2022,Delivered,406 GB SSD,SSD,Samsung,4500.0,5850.0,1.0,4500.0,5850.0,Ajay Sharma
5106,144465.0,TR,Sagar Jeur,31/12/2022,Shipped,Intel i3 11th gen.,CPU,Intel,8500.0,11050.0,4.0,34000.0,44200.0,Roshan Kumar
5107,144466.0,UK,Rhushikesh Mane,31/12/2022,Order,4GB Graphic card,Graphic Card,Nvidia,12500.0,16250.0,2.0,25000.0,32500.0,Aarvi Gupta
5108,144467.0,UP,Ashish Kumar,31/12/2022,Processing,158 GB DDR4 RAM,RAM,Hynix,3500.0,4550.0,2.0,7000.0,9100.0,Vijay Singh
5109,144468.0,WB,Javed Akhter,31/12/2022,Delivered,BTX motherboard,Motherboard,Gigabyte,4500.0,5850.0,3.0,13500.0,17550.0,Aadil Khan

In [19]:
data.isnull().sum()

Order_Number           15
State_Code             15
Customer_Name          15
Order_Date             15
Status                 15
Product                15
Category               15
Brand                  15
Cost                   15
Sales                  15
Quantity               15
Total_Cost             15
Total_Sales            15
Assigned Supervisor    15
dtype: int64

In [20]:
# dropna is a function used to drop the null values from the databse 
# dropna inplace = true all data will vbe deleted

In [21]:
# check duplicated

In [22]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5105    False
5106    False
5107    False
5108    False
5109    False
Length: 5110, dtype: bool

In [23]:
data[data['Order_Number'].duplicated()]

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# EDA

In [25]:
# total cost=cost*qty

# top 10 category by sales

In [26]:
print("\n Top catgeories by sales :" )
print(data.groupby('Category')['Total_Sales'].sum().sort_values(ascending=False).head(10))

 Top catgeories by sales :
Category
Monitor         23297105.0
CPU             18760300.0
Graphic Card    13113100.0
HDD             12886250.0
SSD             10191350.0
Mouse            3831893.0
RAM              3154697.0
Motherboard      3106545.0
Cabinet          2947594.0
Printer          2873052.0
Name: Total_Sales, dtype: float64

In [27]:
#top 10 Brands

In [28]:
print("\n Top Brands by sales :" )
print(data.groupby('Brand')['Total_Sales'].sum().sort_values(ascending=False).head(10))

 Top Brands by sales :
Brand
Intel              18760300.0
Samsung            16166345.0
Dell               14235195.0
Nvidia             13113100.0
Western Digital     8050250.0
Acer                6558630.0
Gigabyte            5886855.0
Hynix               5538520.0
Seagate             4836000.0
MSI                 3205254.0
Name: Total_Sales, dtype: float64

In [29]:
# monthly sales trend

In [30]:
import matplotlib.pyplot as plt

In [31]:
monthly_sales=data.groupby('Order_Date')['Total_Sales'].sum()

In [32]:
monthly_sales

Order_Date
01/01/2021     391651.0
01/01/2022     308997.0
01/02/2020     126880.0
01/02/2021      38415.0
01/02/2022      22438.0
                ...
31/10/2021      13650.0
31/10/2022      13650.0
31/12/2020       2184.0
31/12/2021    1103700.0
31/12/2022    1362062.0
Name: Total_Sales, Length: 1086, dtype: float64

In [33]:
# state sales

In [34]:
state_Sales=data.groupby('State_Code')['Total_Sales'].sum()

In [35]:
state_Sales

State_Code
AN      494832.0
AP     1576952.0
AR     1711879.0
AS     1665365.0
BR     4862221.0
CG     1681290.0
CH     1958697.0
DD     1676324.0
DH     1717079.0
DL     5061953.0
GA     1566175.0
GJ     9137726.0
HP     1603667.0
HR     1439191.0
JH     1680003.0
JK     1774526.0
KA     1586442.0
KL     1488617.0
LD     1780298.0
MH    17621084.0
ML     1719848.0
MN     1515852.0
MP     1885910.0
MZ     1874418.0
NL     1534390.0
OR     1811498.0
PB     1632722.0
PY     1763229.0
RJ     1758978.0
SK     1800539.0
TN     3428763.0
TR     3660657.0
UK     1718899.0
UP     9264645.0
WB     1843374.0
Name: Total_Sales, dtype: float64

In [36]:
# supervisor wise sales

In [37]:
supervisor_Sales=data.groupby('Assigned Supervisor')['Total_Sales'].sum()

In [38]:
supervisor_Sales

Assigned Supervisor
Aadil Khan      15730767.0
Aarvi Gupta     18685368.0
Advika Joshi    15253693.0
Ajay Sharma     17801186.0
Roshan Kumar    15887079.0
Vijay Singh     15939950.0
Name: Total_Sales, dtype: float64

In [39]:
# top customers

In [40]:
top_Customers=data.groupby('Customer_Name')['Total_Sales'].sum().sort_values(ascending=False).head(10)

In [41]:
tc=data.groupby('Customer_Name')['Order_Number'].nunique()

In [42]:
tc

Customer_Name
Adhir Samal                122
Aditya Agarwal             121
Ajay Mehta                   1
Ajay Sharma                121
Akhilesh Kumar             122
Amit Singh                 120
Aniruddha Kekapure         121
Ashish Kumar               121
Ashish Pandey              120
Ashwini Adsare             120
Aslam Raza                 120
Atif Siddiqui              120
Bijendra                   121
Binod Kumar                  1
Chandrakant Kasbe          120
Dannana Jhammi             122
Dilip Rathod                 1
Firdoush Jabee             121
Haridas Balraj             121
Jagdeep                    120
Jagjeet Variya               1
Javed Akhter               122
Jay Prakash Kumar          121
Jignesh Mhatre             121
Kranti Bheke               121
Kunal Patra                120
Kundan Kumar               121
Mohammed Abdul Kaleem      120
Moinuddin Saifi            121
Prakash Chamka               1
Rahul Kashyap              120
Rahul Kumar Prajapati      122
Rajesh Variya              120
Rajiv Singh                  1
Rakesh Kumar Sharma        120
Ramkrishna Das Adhikary    121
Ranjeet Kumar              121
Ranjeet Mandal             121
Rhushikesh Mane            122
Rohan Kale                 121
Roshan Zameer              121
Sagar Jeur                 122
Sajal Singhal              122
Shanti Giri                  1
Sharmili Pandit              1
Shivanand Sahani           121
Suvankar Adhikary          122
Suvankar Chakraborty       122
Vijay Mehta                  1
Vijaya singh                 1
Vikas Bhalekar               1
Vinod Bhave                  1
Vinod Mehta                121
Vinod Singh                  1
Vipin Kumar                122
Vishal Singh                 1
Name: Order_Number, dtype: int64

In [43]:
top_Customers

Customer_Name
Rahul Kumar Prajapati      2974621.0
Vipin Kumar                2865746.0
Sajal Singhal              2842554.0
Rakesh Kumar Sharma        2829840.0
Ramkrishna Das Adhikary    2775162.0
Ashwini Adsare             2757859.0
Amit Singh                 2753348.0
Adhir Samal                2751814.0
Kranti Bheke               2746575.0
Aslam Raza                 2740777.0
Name: Total_Sales, dtype: float64

In [44]:
tc=data.groupby('Customer_Name')['Order_Number'].count()

In [45]:
tc

Customer_Name
Adhir Samal                122
Aditya Agarwal             121
Ajay Mehta                   1
Ajay Sharma                121
Akhilesh Kumar             122
Amit Singh                 120
Aniruddha Kekapure         121
Ashish Kumar               121
Ashish Pandey              120
Ashwini Adsare             120
Aslam Raza                 120
Atif Siddiqui              120
Bijendra                   121
Binod Kumar                  1
Chandrakant Kasbe          120
Dannana Jhammi             122
Dilip Rathod                 1
Firdoush Jabee             121
Haridas Balraj             121
Jagdeep                    120
Jagjeet Variya               1
Javed Akhter               122
Jay Prakash Kumar          121
Jignesh Mhatre             121
Kranti Bheke               121
Kunal Patra                120
Kundan Kumar               121
Mohammed Abdul Kaleem      120
Moinuddin Saifi            121
Prakash Chamka               1
Rahul Kashyap              120
Rahul Kumar Prajapati      122
Rajesh Variya              120
Rajiv Singh                  1
Rakesh Kumar Sharma        120
Ramkrishna Das Adhikary    121
Ranjeet Kumar              121
Ranjeet Mandal             121
Rhushikesh Mane            122
Rohan Kale                 121
Roshan Zameer              121
Sagar Jeur                 122
Sajal Singhal              122
Shanti Giri                  1
Sharmili Pandit              1
Shivanand Sahani           121
Suvankar Adhikary          122
Suvankar Chakraborty       122
Vijay Mehta                  1
Vijaya singh                 1
Vikas Bhalekar               1
Vinod Bhave                  1
Vinod Mehta                121
Vinod Singh                  1
Vipin Kumar                122
Vishal Singh                 1
Name: Order_Number, dtype: int64

In [46]:
# EDA

In [47]:
# checking correaltion 
# to see the impact of change in one varibale over other

In [51]:
numeric_cols=['Cost','Sales','Quantity','Total_Cost']
print ("\n correlation matrix")
print(data[numeric_cols].corr())

 correlation matrix
                Cost     Sales  Quantity  Total_Cost
Cost        1.000000  1.000000 -0.021444    0.769306
Sales       1.000000  1.000000 -0.021444    0.769306
Quantity   -0.021444 -0.021444  1.000000    0.517899
Total_Cost  0.769306  0.769306  0.517899    1.000000

In [54]:
# in correlation the max is 1  and min is 0 the 1 denotes that the two variables are 100 
#percent correlated in a positive way whereas - sign denotes there is negative correatlion

In [55]:
# value_Count

In [56]:
#category_frequency

In [59]:
# value count function is a function in pandas which checks the frequency of the particular column

In [60]:
print(data['Category'].value_counts())

Category
Monitor          749
CPU              600
Mouse            599
SSD              450
Graphic Card     450
Cabinet          449
Keyboard         449
HDD              449
RAM              300
Computer Case    150
NIC              150
Printer          150
Motherboard      148
MotherBoard        2
Name: count, dtype: int64

In [61]:
data

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,144464.0,TN,Rahul Kumar Prajapati,31/12/2022,Delivered,406 GB SSD,SSD,Samsung,4500.0,5850.0,1.0,4500.0,5850.0,Ajay Sharma
5106,144465.0,TR,Sagar Jeur,31/12/2022,Shipped,Intel i3 11th gen.,CPU,Intel,8500.0,11050.0,4.0,34000.0,44200.0,Roshan Kumar
5107,144466.0,UK,Rhushikesh Mane,31/12/2022,Order,4GB Graphic card,Graphic Card,Nvidia,12500.0,16250.0,2.0,25000.0,32500.0,Aarvi Gupta
5108,144467.0,UP,Ashish Kumar,31/12/2022,Processing,158 GB DDR4 RAM,RAM,Hynix,3500.0,4550.0,2.0,7000.0,9100.0,Vijay Singh
5109,144468.0,WB,Javed Akhter,31/12/2022,Delivered,BTX motherboard,Motherboard,Gigabyte,4500.0,5850.0,3.0,13500.0,17550.0,Aadil Khan

In [62]:
# z-score

In [63]:
# a z-score is a way that tells how far a data value is from mean of the dataset in terms of sd

In [64]:
# z-score formula = x-mean /sd
# x is the value of the dataset 
# mean is the avergae 
# sd is the sd

# ex: 4,5,6,7,8,9
#mean =4+5+6+7+8+9/6=39/6=6.5
#6.5 is mean 


#to find sd 
x        x-mean               (x-mean)**2
4         -2.5                  6.25
5          -1.5                 2.25
6           -0.5                0.25
7           0.5                 0.25
8           1.5                 2.25
9           2.5                 6.25

add (x-mean)**2=17.5
sd= suqre root of summation (x-x)2/n
=17.5/6=square root of squre 1.707

# before finding the sd 
square root of 17.5/6 = variance sqaure root 2.9 
square root 1.707 
# z-score 
=x-mean/sd 
4 is the first data variable 
z=4-6.5/1.707=-1.46
5:
z=5-6.5/1.707=-0.88
6:
z=6-6.5/1.707=-0.29
7:
z=7-6.5/1.707=-0.29
8:
z=8-6.5/1.707=0.88
9:
z-9-6.5/1.707=1.46

z-score = -2 to +2 = normal 
z score = -3 to +3 = mostly acceptable 
z score = beyond +3 = outlier 
it is only finded on numerical data
it tells us the probability of outliers and also if we have to remnove any data or not

# how to find z score in python

In [65]:
import pandas as pd 
from scipy.stats import zscore

In [66]:
numeric_cols=['Cost','Sales','Quantity','Total_Cost']
for col in numeric_cols:
    data[f'{col}_zscore']=zscore(data[col])

In [67]:
numeric_cols

['Cost', 'Sales', 'Quantity', 'Total_Cost']

In [68]:
data

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor,Cost_zscore,Sales_zscore,Quantity_zscore,Total_Cost_zscore
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma,NaN,NaN,NaN,NaN
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar,NaN,NaN,NaN,NaN
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta,NaN,NaN,NaN,NaN
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh,NaN,NaN,NaN,NaN
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,144464.0,TN,Rahul Kumar Prajapati,31/12/2022,Delivered,406 GB SSD,SSD,Samsung,4500.0,5850.0,1.0,4500.0,5850.0,Ajay Sharma,NaN,NaN,NaN,NaN
5106,144465.0,TR,Sagar Jeur,31/12/2022,Shipped,Intel i3 11th gen.,CPU,Intel,8500.0,11050.0,4.0,34000.0,44200.0,Roshan Kumar,NaN,NaN,NaN,NaN
5107,144466.0,UK,Rhushikesh Mane,31/12/2022,Order,4GB Graphic card,Graphic Card,Nvidia,12500.0,16250.0,2.0,25000.0,32500.0,Aarvi Gupta,NaN,NaN,NaN,NaN
5108,144467.0,UP,Ashish Kumar,31/12/2022,Processing,158 GB DDR4 RAM,RAM,Hynix,3500.0,4550.0,2.0,7000.0,9100.0,Vijay Singh,NaN,NaN,NaN,NaN
5109,144468.0,WB,Javed Akhter,31/12/2022,Delivered,BTX motherboard,Motherboard,Gigabyte,4500.0,5850.0,3.0,13500.0,17550.0,Aadil Khan,NaN,NaN,NaN,NaN

In [70]:
print(data[[f'{col}_zscore' for col in numeric_cols]])

      Cost_zscore  Sales_zscore  Quantity_zscore  Total_Cost_zscore
0             NaN           NaN              NaN                NaN
1             NaN           NaN              NaN                NaN
2             NaN           NaN              NaN                NaN
3             NaN           NaN              NaN                NaN
4             NaN           NaN              NaN                NaN
...           ...           ...              ...                ...
5105          NaN           NaN              NaN                NaN
5106          NaN           NaN              NaN                NaN
5107          NaN           NaN              NaN                NaN
5108          NaN           NaN              NaN                NaN
5109          NaN           NaN              NaN                NaN

[5110 rows x 4 columns]

In [78]:
data.describe()

,Order_Number,Cost,Sales,Quantity,Total_Cost,Total_Sales,Cost_zscore,Sales_zscore,Quantity_zscore,Total_Cost_zscore
count,5095.000000,5095.000000,5095.000000,5095.000000,5095.000000,5095.000000,0.0,0.0,0.0,0.0
mean,141921.000000,6066.123651,7885.960746,2.486948,14991.778214,19489.311678,NaN,NaN,NaN,NaN
std,1470.944141,3952.022039,5137.628651,1.113581,12574.918427,16347.393955,NaN,NaN,NaN,NaN
min,139374.000000,350.000000,455.000000,1.000000,350.000000,455.000000,NaN,NaN,NaN,NaN
25%,140647.500000,2100.000000,2730.000000,2.000000,4500.000000,5850.000000,NaN,NaN,NaN,NaN
50%,141921.000000,6550.000000,8515.000000,2.000000,10720.000000,13936.000000,NaN,NaN,NaN,NaN
75%,143194.500000,8500.000000,11050.000000,3.000000,22950.000000,29835.000000,NaN,NaN,NaN,NaN
max,144468.000000,14500.000000,18850.000000,4.000000,58000.000000,75400.000000,NaN,NaN,NaN,NaN

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Number         5095 non-null   float64
 1   State_Code           5095 non-null   object
 2   Customer_Name        5095 non-null   object
 3   Order_Date           5095 non-null   object
 4   Status               5095 non-null   object
 5   Product              5095 non-null   object
 6   Category             5095 non-null   object
 7   Brand                5095 non-null   object
 8   Cost                 5095 non-null   float64
 9   Sales                5095 non-null   float64
 10  Quantity             5095 non-null   float64
 11  Total_Cost           5095 non-null   float64
 12  Total_Sales          5095 non-null   float64
 13  Assigned Supervisor  5095 non-null   object
 14  Cost_zscore          0 non-null      float64
 15  Sales_zscore         0 non-null      float64
 16  Quantity_zscore      0 non-null      float64
 17  Total_Cost_zscore    0 non-null      float64
dtypes: float64(10), object(8)
memory usage: 718.7+ KB

In [82]:
print(data['Sales'].std())

5137.6286509549755

In [83]:
print(data['Cost'].std())

3952.0220391961725

In [84]:
data['Sales'].mean()

np.float64(7885.960745829244)

In [88]:
from scipy.stats import zscore
import numpy as np
numeric_data = data.select_dtypes(include=np.number)
z_scores = np.abs(zscore(numeric_data))

outliers_z = (z_scores).sum(axis=0)

print(outliers_z)

[nan nan nan nan nan nan nan nan nan nan]